<? if ($this->lent) { ?>
    <?= $this->owner ?> says that you lent them &pound;<?= $this->loanAmount ?>.
<? } else { ?>
    <?= $this->owner ?> says that you borrowed &pound;<?= $this->loanAmount ?> from them.
<? } ?>

Is this true?

<form method="post" action="/purchase/respondtoloanproposal">
    <input type="hidden" name="loanId" value="<?= $this->loanId ?>">
    <input type="hidden" name="updatedBy" value="<?= $this->updatedBy ?>">

    <input type="submit" class="btn btn-success" value="Accept" name="reply">
    <input type="submit" class="btn btn-danger" value="Reject" name="reply">
</form>