<?= $this->loanee ?> says they have repaid you &pound;AMOUNT. Is this true?

This will reduce their debt to..

<form method="post" action="/purchase/respondtoloanpayment">
    <input type="hidden" name="loanId" value="<?= $this->loanId ?>">
    <input type="hidden" name="updatedBy" value="<?= $this->updatedBy ?>">

    <input type="submit" class="btn btn-success" value="Accept" name="reply">
    <input type="submit" class="btn btn-danger" value="Reject" name="reply">
</form>