<? $stepToDisplay = false; ?>

<? if ($this->stepNum == 5) { ?>
    <? $stepToDisplay = 5; ?>
<? } else { ?>
    <? foreach ($this->steps as $step) { ?>
        <? $isThisStep = $step->id === $this->stepNum; ?>

        <? if ($step->id != 5) { ?>
            <div class="<?= $isThisStep ? 'highlighted' : '' ?>">
                <? if (!is_null($step->receiver_title) && (($this->userId != $this->owner))) { ?>
                    <?= $step->step . ' ' . $step->receiver_title ?>
                <? } else if ($this->userId == $this->loan->loanee_id) { ?>
                    <?= $step->step . ' ' . $step->loanee_title ?>
                <? } else { ?>
                    <?= $step->step . ' ' . $step->loaner_title ?>
                <? } ?>
            </div>
        <? } ?>

        <? if ($isThisStep) { ?>
            <? $stepToDisplay = $step->id; ?>
        <? } ?>
    <? } ?>
<? } ?>

<? if ($stepToDisplay == 1 && ($this->userId != $this->owner)) { ?>
    <?= $this->partial('purchase', 'loanproposalreplyform', array(
        'lent'       => $this->loan->loaner_id == $this->userId,
        'owner'      => $this->loan->owner_name,
        'loanAmount' => $this->loan->total_amount,
        'loanId'     => $this->loan->id,
        'updatedBy'  => $this->userId
    )); ?>

<? } else if ($stepToDisplay == 2 && ($this->userId == $this->loan->loanee_id)) { ?>
    <?= $this->partial('purchase', 'loanpaymentform', array(
        'loanAmount' => $this->loan->amount_remaining,
        'loanId'     => $this->loan->id,
        'updatedBy'  => $this->userId
    )); ?>

<? } else if ($stepToDisplay == 3 && ($this->userId == $this->loan->loaner_id)) { ?>
    <?= $this->partial('purchase', 'loanpaymentacceptanceform', array(
        'loanee'     => $this->loan->loanee,
        'loanAmount' => $this->loan->amount_remaining,
        'updatedBy'  => $this->userId
    )); ?>

<? } else if ($stepToDisplay == 5) { ?>
    you got rejected
<? } ?>