<style>
.mapOverallStats {
    text-align: center;
    font-size: 24px;
}
.smlP {
    font-size: 14px;
}
</style>

<div class="row topbar" style="margin-bottom:20px;">
    <div class="col-md-2 col-md-offset-10">
        Filter By Team Size 
        <select id="teamSizeFilter" class="form-control">
            <option> All </option>
            <option> 5 </option>
            <option> 4 </option>
            <option> 3 </option>
            <option> 2 </option>
        </select>
    </div>
</div>

<div class="row">
    <div class="col-md-10">
        <div class="col-md-12">
            <div id="mapsContainer">
            </div>
        </div>
        <div class="col-md-4">
            <b>Summary</b>
            <textarea class="form-control" id="summary" style="resize: vertical;"></textarea>
        </div>
    </div>
    
    <div class="col-md-2">
        <div id="matchTicker" style="max-height: 700px; height: 700px; overflow: auto;">
        </div>
    </div>
<div>