<? if (!($this->showErrors)) { ?>
    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-6">
            <h2> Uh Oh</h2>
            <p>
                Sorry, it looks like something is wrong with this page (or it doesn't exist!)
            </p>
        </div>
        <div class="col-md-3"></div>
    </div>
<? } else { ?>
    <h1>An error occurred</h1>
    <h2><?php echo $this->message ?></h2>

    <?php if (isset($this->exception)): ?>

        <h3>Exception information:</h3>
        <p>
            <b>Message:</b> <?php echo $this->exception->getMessage() ?>
        </p>

        <h3>Stack trace:</h3>
        <pre><?php echo $this->exception->getTraceAsString() ?>
  </pre>

        <h3>Request Parameters:</h3>
        <pre><?php echo $this->escape(var_export($this->request->getParams(), true)) ?>
  </pre>

    <?php endif ?>
<? } ?>