<div class="bracketContainer">
    <div class="semis">
        <div class="bracket-header">Semifinals (Bo3)</div>
        <div class="bracket-game">
            <span class="glyphicon glyphicon-info-sign glyphicon-20" id="semi_final_game_1"></span>
            <div class="player-top loser">
                <div class="name"><img src="https://minotar.net/avatar/Nitro_Grande/32">Nitro_Grande</div>
                <div class="score">1</div>
            </div>
            <div class="player-bottom winner">
                <div class="name"><img src="https://minotar.net/avatar/Cyclone06/32">Cyclone06</div>
                <div class="score">2</div>
            </div>

            <div class="bracket-game-details hidden" id="semi_final_game_1_maps">
                <div class="title">
                    <b>Nitro_Grande</b> vs <b>Cyclone06</b>
                    <p>2012-08-18</p>
                </div>
                <div class="ticksLeft">
                    <div class="miniRow"></div>
                    <div class="miniRow"></div>
                    <div class="miniRow"><span class="glyphicon glyphicon-ok"></span></div>
                </div>
                <div class="mapNames">
                    <div class="miniRow">Fatal Attraction</div>
                    <div class="miniRow">Labyrinth</div>
                    <div class="miniRow">Dm_Agony</div>
                </div>
                <div class="ticksRight">
                    <div class="miniRow"><span class="glyphicon glyphicon-ok"></span></div>
                    <div class="miniRow"><span class="glyphicon glyphicon-ok"></span></div>
                    <div class="miniRow"></div>
                </div>
            </div>

        </div>
        <div class="bracket-game bracket-bottom">
            <span class="glyphicon glyphicon-info-sign glyphicon-20" id="semi_final_game_2"></span>
            <div class="player-top loser">
                <div class="name"><img src="https://minotar.net/avatar/ZedHeadEd/32">ZedHeadEd</div>
                <div class="score">1</div>
            </div>
            <div class="player-bottom winner">
                <div class="name"><img src="https://minotar.net/avatar/Zvede/32">Zvede</div>
                <div class="score">2</div>
            </div>

            <div class="bracket-game-details hidden" id="semi_final_game_2_maps">
                <div class="title">
                    <b>ZedHeadEd</b> vs <b>Zvede</b>
                    <p>2012-08-18</p>
                </div>
                <div class="ticksLeft">
                    <div class="miniRow"><span class="glyphicon glyphicon-ok"></div>
                    <div class="miniRow"></div>
                    <div class="miniRow"></span></div>
                </div>
                <div class="mapNames">
                    <div class="miniRow">Melon Sprurdles</div>
                    <div class="miniRow">Quizzle Cave</div>
                    <div class="miniRow">Day Of Defeat</div>
                </div>
                <div class="ticksRight">
                    <div class="miniRow"></div>
                    <div class="miniRow"><span class="glyphicon glyphicon-ok"></span></div>
                    <div class="miniRow"><span class="glyphicon glyphicon-ok"></span></div>
                </div>
            </div>
        </div>
    </div>
    <div class="finals">
        <div class="bracket-header">Finals (Bo5)</div>
        <div class="bracket-game">
            <span class="glyphicon glyphicon-info-sign glyphicon-20" id="final_game"></span>
            <div class="player-top loser">
                <div class="name"><img src="https://minotar.net/avatar/Cyclone06/32">Cyclone06</div>
                <div class="score">1</div>
            </div>
            <div class="player-bottom winner">
                <div class="name"><img src="https://minotar.net/avatar/Zvede/32">Zvede</div>
                <div class="score">3</div>
            </div>

            <div class="bracket-game-details hidden" id="final_game_maps">
                <div class="title">
                    <b>Cyclone06</b> vs <b>Zvede</b>
                    <p>2012-09-13</p>
                </div>
                <div class="ticksLeft">
                    <div class="miniRow"></div>
                    <div class="miniRow"><span class="glyphicon glyphicon-ok"></span></div>
                    <div class="miniRow"></div>
                    <div class="miniRow"><span class="glyphicon glyphicon-minus"></span></div>
                    <div class="miniRow"><span class="glyphicon glyphicon-minus"></span></div>
                    <div class="miniRow"></div>
                </div>
                <div class="mapNames">
                    <div class="miniRow">Pan's Playground</div>
                    <div class="miniRow">Challenge #6</div>
                    <div class="miniRow">Mt. Nargasaur</div>
                    <div class="miniRow">Rainbow Road Art Facility</div>
                    <div class="miniRow">Quizzle Cave</div>
                    <div class="miniRow">Melon Sprurdles</div>
                </div>
                <div class="ticksRight">
                    <div class="miniRow"><span class="glyphicon glyphicon-ok"></span></div>
                    <div class="miniRow"></div>
                    <div class="miniRow"><span class="glyphicon glyphicon-ok"></span></div>
                    <div class="miniRow"><span class="glyphicon glyphicon-minus"></span></div>
                    <div class="miniRow"><span class="glyphicon glyphicon-minus"></span></div>
                    <div class="miniRow"><span class="glyphicon glyphicon-ok"></span></div>
                </div>
            </div>
        </div>
    </div>
</div>