<div class="row">
    <div class="col-md-12">

        <? foreach ($this->seasons as $seasonNumber => $season) { ?>
            <div class="season">
                <h3>
                    <? if ($seasonNumber == 6) { ?>
                        SutoNarg Ultimate Minecrafter Tournament
                    <? } else { ?>
                        Season <?= $seasonNumber ?>
                    <? } ?>
                </h3>
                <div class="episodes">
                    <? foreach ($season['episodes'] as $episode) { ?>

                        <a href="#episode_<?= $episode->episode_id ?>" class="popup-trigger">
                            <img src="http://img.youtube.com/vi/<?= $episode->video_id ?>/hqdefault.jpg" class="youtube-thumb">
                        </a>

                        <div id="episode_<?= $episode->episode_id ?>" class="white-popup-block zoom-anim-dialog mfp-hide">
                            <div class="modal_header">
                                Season <?= $seasonNumber ?>
                                <?= $episode->is_finale ? ' Finale' : 'Episode ' . $episode->episode_number ?>
                            </div>
                            <div class="modal_content row">
                                <a href="https://www.youtube.com/watch?v=<?= $episode->video_id ?>">
                                    <img src="http://img.youtube.com/vi/<?= $episode->video_id ?>/hqdefault.jpg"
                                         class="youtube-video">
                                </a>

                                <div class="modal_episode_details">
                                    <h3>Details</h3>
                                    <div class="detail_subsection">
                                        Episode Number (Overall): <?= $episode->episode_id ?>
                                    </div>
                                    <div class="detail_subsection">
                                        Episode Number (In Series): <?= $episode->episode_number ?>
                                    </div>
                                    <div class="detail_subsection">
                                        Date of Upload: <?= $episode->datetime ?>
                                    </div>
                                    <div class="detail_subsection">
                                        <a href="https://www.youtube.com/watch?v=<?= $episode->video_id ?>">
                                            Watch On YouTube
                                        </a>
                                    </div>
                                </div>
                                <div class="modal_episode_participants">
                                    <h3> Participants </h3>
                                    <? foreach ($episode->participants as $participant) { ?>
                                        <?= $this->partial('sutonarg', 'player_face', array(
                                            'name' => $participant->name,
                                            'won'  => $participant->player_id == $episode->winner_id
                                        )); ?>
                                    <? } ?>
                                </div>
                                <div class="modal_episode_challenges">
                                    <h3> Challenges </h3>
                                    <? foreach ($episode->challenges as $challenge) { ?>
                                        <div class="challenge">
                                            <img src="<?= $challenge->icon_url ?>">
                                            <?= $challenge->challenge_name ?>
                                        </div>

                                    <? } ?>
                                </div>
                            </div>

                        </div>
                    <? } ?>
                </div>
            </div>
        <? } ?>
    </div>
</div>