<div class="row">
    <? foreach ($this->players as $player) { ?>
        <div class="col-lg-3 col-md-4 col-sm-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="panel_title">
                        <img src="https://minotar.net/avatar/<?= $player->name ?>/32">
                        <div class="player-name"><?= $player->name ?></div>
                    </div>
                    <div class="clear"></div>
                    <b>Appeared on</b>
                    <div class="listofepisodes">
                        <? foreach ($player->appearances as $appearance) { ?>
                            <div class="episode">
                                <? if ($appearance->season_number == 6) { ?>
                                    Winner's Tournament
                                <? } else { ?>
                                    Season <?= $appearance->season_number ?>
                                <? } ?>
                                <?= ($appearance->is_finale) ? 'Finale' : 'Episode ' . $appearance->episode_number?>
                                <? if ($appearance->winner_id === $player->player_id) { ?>
                                    <i class="fa fa-trophy"></i>
                                <? } ?>
                            </div>
                        <? } ?>
                    </div>
                </div>
            </div>
        </div>
    <? } ?>
</div>