<?
/**
 * Name - year.phtml
 * Author - Craig Knott
 * Description - Draw all modules of a year in condensed format
 * Params - {
 *     $this->width: Number of columns the panel will take up (1-12)
 *     $this->semesters: Array of semesters (with sub arrays of modules)
 *     $this->grade: Total grade for this year (0-100)
 *     $this->wGrade: How much this year contributes to the degree
 *     $this->yearNumber: Year of study
 * }
 */
?>
<?
    $panelType = "default";

    if ($this->grade > 0) {
        $panelType = "danger";
    }
    if ($this->grade >= 40) {
        $panelType = "warning";
    }
    if ($this->grade >= 70) {
        $panelType = "success";
    }
?>

<div class="col-md-<?= $this->width ?>">
    <div class="panel panel-<?= $panelType ?>">
        <div class="panel-heading text-center">
            <?= $this->yearNumber . ordinalSuffix($this->yearNumber) ?> Year
        </div>
        <div class="panel-body">
            <? foreach ($this->semesters as $semesterName => $modules) { ?>
                <? if (count($modules) == 0 ) { ?>
                    <? continue; ?>
                <? } ?>
                <table class="table">
                    <thead>
                    <tr>
                        <th colspan="2">
                            <?= $semesterName ?>
                        </th>
                    </tr>

                    </thead>
                    <tbody>

                    </tbody>
                    <? foreach ($modules as $module) { ?>
                        <tr>
                           <td>
                                <?= $module->code ?>
                           </td>
                            <td>
                                <?= $module->grade ?>
                            </td>
                        </tr>
                    <? } ?>
                </table>
            <? } ?>
            <div class="row contributionContainer text-center">
                <div class="col-md-6">
                    <div class="title">
                        Grade Average For Year
                    </div>
                    <div class="contribution">
                        <?= number_format($this->grade, 2) ?>%
                    </div>
                </div>

                <div class="col-md-6">
                    <div class="title">
                        Final Degree Contribution
                    </div>
                    <div class="contribution">
                        <?= number_format($this->wGrade, 2) ?>%
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>