<li class="navLink dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
        <i class="fa fa-bell"></i> <span class="text">Notifications</span>

        <span class="badge">1</span></a>
    <ul class="dropdown-menu">
        <li class="dropdown-header">New Notifications</li>

        <li style="color: #FFB347;">
            <a href="/admin/index" style="color: #FFB347;">
                <i class="fa fa-comment"></i>
                <b> cxk </b> commented on your route "Nice Canal Drive"
            </a>
        </li>
        
        <li role="separator" class="divider"></li>
        
        <li>
            <a href="/admin/index">
                <i class="fa fa-clone"></i>
                <b> cxk </b> cloned your route "Nice Canal Drive"
            </a>
        </li>

        <li>
            <a href="/admin/index">
                <i class="fa fa-comment"></i>
                <b> abxow </b> commented on your route "Nice Canal Drive"
            </a>
        </li>

        <li>
            <a href="/admin/index">
                <i class="fa fa-comment"></i>
                <b> ralph007 </b> commented on your route "Mountain Range Drive"
            </a>
        </li>

        <li>
            <a href="/admin/index">
                <i class="fa fa-download"></i>
                <b> ralph007 </b> downloaded your route "Mountain Range Drive"
            </a>
        </li>
    </ul>
</li>