<div class="row">
    <div class='col-md-6'>
        <label>Course Length</label>
        <div class="input-group">
            <input type="number" id="in_courseLength" class="form-control" aria-describedby="yrs_addon"
                   value="<?= $this->settings->course_length ?>">
            <span class="input-group-addon" id="yrs_addon">Years</span>
        </div>
    </div>

    <div class='col-md-6'>
        <label>Default Tab</label>
        <div class="form-group">
            <select class="form-control" id="in_defaultTab">
                <? for ($i = 1; $i <= $this->settings->course_length; $i++) { ?>
                    <option
                        <?= $i == $this->settings->default_tab ? 'selected="selected"' : '' ?>
                        value="id_year<?= $i ?>">
                        Year <?= $i ?>
                    </option>
                <? } ?>
            </select>
        </div>
    </div>

    <div class="col-md-12">
        <div class="yearWeightsTitle">
            Weight of Years
            <a href="#" data-toggle="tooltip"
               title="Combined sum must be less than or equal to 100">
                [?]
            </a>
        </div>
    </div>
    <? foreach ($this->yearsAndWeights as $year) { ?>
        <? if ($year->yearOfStudy <= $this->settings->course_length) { ?>
            <div class="col-md-6">
                <div class="input-group">
                    <span class="input-group-addon" id="yr_prefix<?= $year->id ?>">
                        Year <?= $year->yearOfStudy ?>
                    </span>
                    <input type="number" class="form-control yearWeight"
                           aria-describedby="yr_prefix<?= $year->id ?>"
                           id="yearOfStudy_<?= $year->id ?>"
                           value="<?= $year->weight ?>">
                </div>
            </div>
        <? } ?>
    <? } ?>

    <div class="col-md-12 noBtmMargin">
        <input id="updateGrades" type="submit" class="btn btn-success" value="Submit"/>
    </div>
</div>