<div class="row">
    <div class="col-md-12 noBtmMargin">
        <label>Name</label>
    </div>
    <div class="col-md-6">
        <input type="text" class="form-control" id="in_fname" value="<?= $this->user->firstName ?>"
               placeholder="First Name">
    </div>
    <div class="col-md-6">
        <input type="text" class="form-control" id="in_lname" value="<?= $this->user->lastName ?>" placeholder="Last Name">
    </div>

    <div class="col-md-12">
        <label> Email </label>
        <div class="input-group">
            <span class="input-group-addon" id="email_addon">@</span>
            <input type="text" id="in_email" class="form-control" aria-describedby="email_addon"
                   value="<?= $this->user->email ?>" placeholder="Email">
        </div>
    </div>

    <div class="col-md-12">
        <input id="updateAccount" type="submit" class="btn btn-success" value="Submit"/>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <label> Change Password</label>
        <div class="form-group" id="in_curPassWrapper">
            <input type="password" class="form-control" id="in_curPass" placeholder="Enter Current Password">
        </div>
    </div>
    <div class="col-md-6">
        <div class="form-group" id="in_newPass1Wrapper">
            <input type="password" class="form-control" id="in_newPass1" placeholder="Enter New Password">
        </div>
    </div>
    <div class="col-md-6">
        <div class="form-group" id="in_newPass2Wrapper">
            <input type="password" class="form-control" id="in_newPass2" placeholder="Confirm New Password">
        </div>
    </div>

    <div class="col-md-9 noBtmMargin">
        <div class="alert alert-danger hidden" role="alert" id="errorDisplay"></div>
    </div>
    <div class="col-md-3 noBtmMargin">
        <input id="updatePassword" type="submit" class="btn btn-success" value="Change Password"/>
    </div>
</div>
