<div class="row">
    <? if ($this->showMsg === 'ftu') { ?>
        <div class="col-md-12 ftuBanner">
            <div class="alert alert-danger" role="alert">
                To begin using the revision application, you need to enter at least one revision period.
            </div>
        </div>
    <? } else { ?>
        <div class="col-md-12">
            <div class="table-responsive">
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th> Name</th>
                        <th> Start Date</th>
                        <th> End Date</th>
                        <th> Manage</th>
                    </tr>
                    </thead>
                    <tbody id="periods_tbody">
                    </tbody>
                </table>
            </div>
        </div>
    <? } ?>
    <hr>
    <div class="addExamForm">
        <div class="col-md-4">
            <label>Name</label>
            <div class="form-group" id="period_nameWrapper">
                <input type="text" class="form-control" id="period_name" placeholder="Name of period">
            </div>
        </div>
        <div class="col-md-4">
            <label>Start Date</label>
            <div class="form-group" id="start_dateWrapper">
                <input type="text" class="form-control" id="start_date" placeholder="">
            </div>
        </div>
        <div class="col-md-4">
            <label>End Date</label>
            <div class="form-group" id="end_dateWrapper">
                <input type="text" class="form-control" id="end_date" placeholder="">
            </div>
        </div>
        <div class="col-md-12">
            <div class="col-md-12 noBtmMargin">
                <input id="addExamPeriod" type="submit" class="btn btn-success" value="Add Period"/>
            </div>
        </div>
    </div>
</div>