<input type="hidden" id="workoutId" value="<?= $this->workoutId ?>">

<div class="row">
    <div class="col-xs-12 text-center title">
        <h3>Exercise Selector</h3>
    </div>
</div>

<div class="row">
    <div class="col-xs-12 text-center" id="loadingGif">
        <img src="/images/global/loading.gif">
    </div>
    <div class="col-xs-12">
        <div class="list-group" id="listGroup">
        </div>
    </div>
</div>