<div class="panel-group">
    <? if (count($this->exercises) == 0) { ?>
        <div class="alert alert-warning alert-dismissible fade in" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            <strong>Nothing here yet!</strong> Start adding exercises, and you'll see them displayed here.
        </div>
    <? } else { ?>
        <? foreach ($this->exercises as $i => $exercise) { ?>
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4 class="panel-title">
                        <a data-toggle="collapse" data-parent="#accordion"
                           href="#collapse_el_<?= $this->workoutId ?>_<?= $i ?>">
                            <?= $exercise['name'] ?>
                        </a>
                    </h4>
                </div>
                <div id="collapse_el_<?= $this->workoutId ?>_<?= $i ?>" class="panel-collapse collapse">
                    <ul class="list-group">
                        <? foreach ($exercise['sets'] as $set) { ?>
                            <li class="list-group-item">
                                <?= $set->reps . ' x ' . $set->weight . ' kg' ?>
                            </li>
                        <? } ?>
                    </ul>
                </div>
            </div>
        <? } ?>
    <? } ?>
</div>