<div class="row">
    <div class="col-md-12 text-center fitnessTitle">
        <h1>
            Fitness Tracker
            <? if ($this->user->userType == 0) { ?>
                <a href="/fitness/add">+</a>
            <? } ?>
        </h1>

    </div>

    <div class="col-md-6 workoutContainer first">
        <a href="/fitness/workout/createNew/1">
            <div class="panel panel-default workout" id="newWorkout">
                <div class="panel-body">
                    New Workout
                </div>
            </div>
        </a>
    </div>

    <div class="col-md-6 workoutContainer">
        <a href="/fitness/previous">
            <div class="panel panel-default workout" id="oldWorkout">
                <div class="panel-body">
                    See stats
                </div>
            </div>
        </a>
    </div>
</div>