<input type="hidden" value="<?= $this->workoutId ?>" id="workoutId">
<input type="hidden" value="<?= $this->exerciseId ?>" id="exerciseId">

<div class="row">
    <div class="col-xs-12 text-center title">
        <h3> <?= $this->exerciseName ?> </h3>
    </div>

    <div class="col-xs-12">
        <div class="form-group">
            <label> Reps </label>
            <div class="reps pull-right">
                <span id="repsVal">0</span>
            </div>

            <div class="btn-group btn-group-justified" role="group">
                <? foreach ($this->repIntervals as $i => $repInterval) { ?>
                    <div class="btn-group">
                        <button type="button" class="btn btn-default addReps">
                            <span class="sign">+</span><span class="val"><?= $repInterval ?></span>
                        </button>
                    </div>
                <? } ?>
            </div>
            <div class="btn-group btn-group-justified" role="group">
                <? foreach ($this->repIntervals as $i => $repInterval) { ?>
                    <div class="btn-group">
                        <button type="button" class="btn btn-default minusReps">
                            <span class="sign">-</span><span class="val"><?= $repInterval ?></span>
                        </button>
                    </div>
                <? } ?>
            </div>

        </div>
        <div class="form-group">
            <label> Weight </label>
            <div class="weight pull-right">
                <span id="weightVal">0</span>kg
            </div>

            <div class="btn-group btn-group-justified" role="group">
                <? foreach ($this->weightIntervals as $i => $weightInterval) { ?>
                    <div class="btn-group">
                        <button type="button" class="btn btn-default addWeight">
                            <span class="sign">+</span><span class="val"><?= $weightInterval ?></span>
                        </button>
                    </div>
                <? } ?>
            </div>
            <div class="btn-group btn-group-justified" role="group">
                <? foreach ($this->weightIntervals as $i => $weightInterval) { ?>
                    <div class="btn-group">
                        <button type="button" class="btn btn-default minusWeight">
                            <span class="sign">-</span><span class="val"><?= $weightInterval ?></span>
                        </button>
                    </div>
                <? } ?>
            </div>
        </div>
        <div class="form-group text-center">
            <button class="btn btn-success" id="setAddButton">
                Add Set
            </button>
        </div>
    </div>

    <div class="row compare">
        <div class="col-xs-12">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th class="text-center">
                        This Time
                    </th>
                    <th class="text-center">
                        Last Time
                    </th>
                </tr>
                </thead>
                <tbody id="setsTbody">
                    <? foreach ($this->lastWorkout as $lastWorkout) { ?>
                        <tr class="text-center">
                            <td></td>
                            <td>
                                <?= $lastWorkout->reps . ' x ' . $lastWorkout->weight . ' kg' ?>
                            </td>
                        </tr>
                    <? } ?>
                </tbody>
            </table>
        </div>
    </div>

    <div class="col-xs-12">
        <div class="form-group text-center">
            <a href="/fitness/workout/workoutId/<?= $this->workoutId ?>">
                <button class="btn btn-success" id="setAddButton">
                    Finished
                </button>
            </a>
        </div>
    </div>
</div>



