<div class="row">
    <div class="col-xs-12 text-center title">
        <h3>Your Workout Today (<?= date("d/m") ?>)</h3>
    </div>

    <div class="col-xs-12">
        <?= $this->action('exerciselist', 'fitness', null, array(
            'workoutId' => $this->workoutId
        )); ?>
    </div>

    <div class="col-xs-12 text-center">
        <a href="/fitness/exercise/workoutId/<?= $this->workoutId ?>">
            <button class="btn btn-primary">
                Add Exercise
            </button>
        </a>
    </div>
</div>



