<div class="hidden" id="hiddenPasswordForm">
    <? if (!is_null($this->errorMessage)) { ?>
        <div class="alert alert-danger" role="alert">
            <i class="fa fa-exclamation-circle"></i>
            <?= $this->errorMessage; ?>
        </div>
    <? } ?>
    <? if (!is_null($this->successMessage)) { ?>
        <div class="alert alert-success" role="alert">
            <i class="fa fa-check"></i>
            <?= $this->successMessage; ?>
        </div>
    <? } ?>
    <?= $this->passwordForm ?>
</div>

<input type="hidden" id="passwordLaunch">