<div class="row">
    <div class="col-md-3 col-sm-2 col-xs-1"></div>
    <div class="col-md-6 col-sm-8 col-xs-10">
        <div class="panel panel-primary">
            <div class="panel-body">
                <h2>
                    <i class="fa fa-cogs"></i> Down for Maintenance
                </h2>
                <p>
                    Unfortunately, Niceway.to is down for maintenence at the moment.
                </p>
                <p>
                    We're always working to upgrade the website and add awesome new features, so check back soon to
                    see what's been added!
                </p>
            </div>
        </div>
    </div>
    <div class="col-md-3 col-sm-2 col-xs-1"></div>
</div>