<div class="row">
    <div class="col-lg-4 col-md-3"></div>
    <div class="col-lg-4 col-md-6">
        <div class="well">
            <h2 class="title">Log in to Niceway.to</h2>
            <div class="row">
                <div class="col-sm-1 col-xs-2">
                </div>
                <div class="col-sm-10 col-xs-8">
                    <?= $this->loginForm; ?>
                    <div class="orSignup">
                        <p>or</p>
                        <a href="/member/signup">
                            <input type="button" class="btn btn-primary signupBtn" value="Sign Up">    
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>