<div class="hidden" id="hiddenSignupForm">
    <? if (!is_null($this->errorMessage)) { ?>
        <div class="alert alert-danger" role="alert">
            <i class="fa fa-exclamation-circle"></i>
            <?= $this->errorMessage; ?>
        </div>
    <? } ?>
    <? if (!is_null($this->infoMessage)) { ?>
        <div class="alert alert-warning" role="alert">
            <i class="fa fa-exclamation-circle"></i>
            <?= $this->infoMessage; ?>
        </div>
    <? } ?>

    <?= $this->signupForm ?>
</div>

<input type="hidden" id="signupLaunch">