<input type="hidden" value="<?= ($this->routeExists) ? $this->routeId : '' ?>" id="routeId">
<input type="hidden" value="<?= $this->user->location ?>" id="userLocation">
<input type="hidden" value="<?= ($this->routeExists) ? $this->latlng->lat : '' ?>" id="center_map_lat">
<input type="hidden" value="<?= ($this->routeExists) ? $this->latlng->lng : '' ?>" id="center_map_lng">
<input type="hidden" value="<?= $this->readOnly ?>" id="mapReadOnly">
<input type="hidden" value="<?= $this->startMapAt ?>" id="startMapAt">

<div id="map"></div>
<div id="left-hand-display">
    <i class="fa fa-compress" id="hide_lhd"></i>
    <div class="title">
        <h3 class="pointsTitle">
            <?= ($this->routeExists) ?
                '<span>' . $this->route->name . '</span> <i class="fa fa-pencil"></i>'
                : "Your Points"
            ?>
        </h3>
        <? if ($this->routeExists) { ?>
            <div class="input-group hidden" id="routeName_2">
                <input type="text" class="form-control" aria-describedby="basic-addon" value="<?= $this->route->name ?>">
                <span class="input-group-addon" id="basic-addon"><i class="fa fa-check"></i></span>
            </div>
        <? } ?>
        <div class="subtitle-buffer"></div>
    </div>
    <div class="navbar-stripe"></div>
    <div class="mapCentre">
        <div class="input-group">
            <input type="text" class="form-control" aria-describedby="search-addon" id="centreMap"
                   placeholder="Centre Map">
            <span class="input-group-addon" id="search-addon"><i class="fa fa-search"></i></span>
        </div>

    </div>
    <div class="navbar-stripe"></div>
    <div class="noPointsYet">
        You haven't added any points yet, click the map to get started!
    </div>
    <div class="fileUpload uploadButton noPointsYet">
        <form id="uploadForm" action="/route/upload" method="POST" enctype="multipart/form-data">
            <span>Or upload from a file</span>
            <input type="file" name="file" class="upload" id="fileUploader"/>
        </form>
    </div>

    <div class="pointsList"></div>
    <div href="#saveroute-popup" class="popup-trigger submit pointsYet hidden">
        Save <?= $this->routeExists ? 'Changes' : 'Route' ?>
    </div>
</div>

<div id="left-hand-display-mini" class="hidden">
    <i class="fa fa-expand" id="show_lhd"></i>
    <div class="title">
        <h3 class="pointsTitle">
            <?= ($this->routeExists) ?
                '<span>' . $this->route->name . '</span> <i class="fa fa-pencil"></i>'
                : "Your Points"
            ?>
        </h3>
        <div class="subtitle-buffer"></div>
    </div>
    <div class="navbar-stripe"></div>
</div>

<div id="saveroute-popup" class="white-popup-block zoom-anim-dialog mfp-hide">
    <h3>
        <i class="fa fa-bookmark"></i> Save your route
    </h3>

    <label>Route Name</label> <span id="noNameError" class="errorMessage hidden">- Route name cannot be blank</span>
    <input type="text" class="form-control" placeholder="Enter a descriptive name" id="routeName"
           value="<?= $this->routeExists ? $this->route->name : '' ?>">

    <div class="textContainer">
        <label>Route Description (optional)</label>
        <textarea placeholder="What are key features of your route? What makes it good?"
                  class="form-control" rows="3" id="routeDesc"><?=
            $this->routeExists ? $this->route->description : ''
            ?></textarea>
    </div>

    <div class="checkContainer">
        <label for="routePrivacy">Select privacy setting:</label>
        <select class="form-control" id="routePrivacy">
            <option value="0" <?= ($this->routeExists && $this->route->is_private) ? '' : 'selected' ?>>
                Public (visible to everyone)
            </option>
            <option value="1" <?= ($this->routeExists && $this->route->is_private) ? 'selected' : '' ?>>
                Private (only visible to you)
            </option>
        </select>
    </div>

    <div class="buttons">
        <button class="btn btn-default" id="submitRoute">
            <i class="fa fa-check"></i> Save
        </button>
        <button class="btn btn-default" id="cancelSubmit">
            Cancel
        </button>
    </div>
    <div class="bottom-filler"></div>
</div>

<div id="loading" class="hidden">
    <div class="loading_body">
        <i class="fa fa-spinner fa-pulse"></i>
        Loading Map <br>
    </div>
</div>
