<input type="hidden" id="email-confirmed" value="<?= ((!is_null($this->user)) && $this->user->isConfirmed) ? 1 : 0 ?>">
<input type="hidden" id="routeId" value="<?= $this->route->routeId ?>">
<input type="hidden" id="ratingId" value="<?= $this->userRouteRating->ratingId ?>">
<input type="hidden" id="userId" value="<?= (!is_null($this->user)) ? $this->user->userId : null ?>">
<input type="hidden" id="username" value="<?= (!is_null($this->user)) ? $this->user->username : null ?>">
<input type="hidden" value="1" id="mapReadOnly">

<div class="row containingRow">
    <div class="col-md-7">
        <div class="row topBar">
            <div class="col-md-8">
                <h3 class="title">
                    <?= $this->route->name ?>
                    <? if (!(is_null($this->user)) && ($this->user->username != $this->route->owner)) { ?>
                        <span id="reportRoute">
                            (<i class="fa fa-flag"></i> Report?)
                        </span>
                    <? } ?>
                </h3>
                <div class="owner">
                    By <?= $this->route->owner ?>
                </div>
            </div>

            <div class="col-md-4">
                <div class="row">
                    <div class="rating" id="ratingContainer">
                        <?= $this->partial('user', 'stars', null, array(
                            'rating'   => $this->route->rating,
                            'fontSize' => '28px'
                        )); ?>
                    </div>
                </div>

                <? if (!(is_null($this->user)) && ($this->user->username != $this->route->owner)) { ?>
                    <div class="row">
                        <div class="yourRating">
                            Your rating
                            <? if ($this->userRouteRating->value > 0) { ?>
                                <span class="clearBtn">
                                    (<i class="fa fa-times"></i>)
                                </span>
                            <? } ?>

                            <?= $this->partial('user', 'stars', null, array(
                                'rating'   => $this->userRouteRating->value,
                                'showId'   => true,
                                'addBreak' => true,
                                'fontSize' => '14px'
                            )); ?>
                        </div>
                    </div>
                <? } ?>
            </div>
        </div>

        <div class="row">
            <div class="col-md-6">
                <div class="thumbnail" id="map">
                </div>

                <div class="border-container border-container-less-pad">
                    <div class="title mediaTitle">
                        Media
                    </div>

                    <? if (!is_null($this->routeMedia) && count($this->routeMedia) > 0) { ?>
                        <div id="mediaCarousel" class="carousel slide" data-ride="carousel">
                            <div class="carousel-inner" role="listbox">
                                <? $i = 0; ?>
                                <? foreach ($this->routeMedia as $m) { ?>
                                    <div class="item<?= $i == 0 ? ' active' : '' ?>">
                                        <img src="<?= $m ?>">
                                    </div>
                                    <? $i++; ?>
                                <? } ?>
                            </div>

                            <a class="left carousel-control" href="#mediaCarousel" role="button" data-slide="prev">
                                <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                                <span class="sr-only">Previous</span>
                            </a>
                            <a class="right carousel-control" href="#mediaCarousel" role="button" data-slide="next">
                                <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                                <span class="sr-only">Next</span>
                            </a>
                        </div>
                    <? } ?>
                </div>
            </div>
            <div class="col-md-6">
                <div class="text-right">
                    <?= $this->partial("route", "action_buttons", null, array(
                        'routeId'     => $this->route->routeId,
                        'user'        => $this->user,
                        'routeOwner'  => $this->route->owner,
                        'isFavourite' => $this->isFavourite
                    )); ?>
                </div>

                <div class="border-container">
                    <div class="title routedetailTitle">
                        Route Details
                    </div>
                    <div>
                        <b>Start</b><br>
                        <span id="start_point" data-latlng="<?= $this->firstPoint ?>"></span>
                    </div>
                    <br>
                    <div>
                        <b>End</b><br>
                        <span id="end_point" data-latlng="<?= $this->lastPoint ?>"></span>
                    </div>
                    <br>
                    <div>
                        <b>Author Description</b><br>
                        <i>
                            <?= ($this->route->description == "") ? "None given" : $this->route->description ?>
                        </i>
                    </div>
                </div>

                <div class="border-container">
                    <div class="title routestatsTitle">
                        Route Stats
                    </div>
                    <div class="stats">
                        <i class="fa fa-comment"></i> <?= $this->route->comments ?> comments
                        <br>
                        <i class="fa fa-star"></i> <?= $this->route->ratings ?> ratings
                        <br>
                        <i class="fa fa-share"></i> <?= $this->route->shares ?> shares
                        <br>
                        <i class="fa fa-download"></i> <?= $this->route->downloads ?> downloads
                        <br>
                        <i class="fa fa-clone"></i> <?= $this->route->forks ?> clones
                    </div>
                </div>
            </div>
        </div>
    </div>

    <?= $this->partial('route', 'social_stream', null, array(
        'user'         => $this->user,
        'route'        => $this->route,
        'socialStream' => $this->socialStream
    )); ?>
</div>