<input type="hidden" id="email-confirmed" value="<?= $this->user->isConfirmed ?>">
<input type="hidden" id="routeId" value="<?= $this->route->routeId ?>">
<input type="hidden" id="ratingId" value="<?= $this->userRouteRating->ratingId ?>">

<div class="row containingRow">
    <div class="col-md-7">
        <div class="row topBar">
            <div class="col-md-8">
                <h3 class="title">
                    <?= $this->route->name ?>
                </h3>
                <div class="owner">
                    By <?= $this->route->owner ?>
                </div>
            </div>

            <div class="col-md-4">
                <div class="rating">
                    <?= $this->partial('user', 'stars', null, array(
                        'rating' => $this->route->rating
                    )); ?>
                </div>
                <? if (!(is_null($this->user)) && ($this->user->username != $this->route->owner)) { ?>
                    <div class="yourRating">
                        Your rating
                        <? if ($this->userRouteRating->value > 0) { ?>
                            <span class="clearBtn">
                                (<i class="fa fa-times"></i>)
                            </span>
                        <? } ?>

                        <?= $this->partial('user', 'stars', null, array(
                            'rating' => $this->userRouteRating->value,
                            'showId' => true
                        )); ?>
                    </div>
                <? } ?>
            </div>
        </div>

        <div class="row">
            <div class="col-md-6">
                <div class="thumbnail">
                    <img src="<?= $this->gmapUrl ?>">
                </div>

                <a class="btnLink" target="_blank" href="/route/openingooglemaps/id/<?= $this->route->routeId ?>">
                    <button class="btn btn-success btn-nopad">
                        <i class="fa fa-street-view"></i> Open in GMaps
                    </button>
                </a>
                <br>
                <? if (!(is_null($this->user))) { ?>
                    <a class="btnLink" href="/route/fork/id/<?= $this->route->routeId ?>">
                        <button class="btn btn-warning btn-nopad">
                            <i class="fa fa-code-fork"></i> Fork Route
                        </button>
                    </a>
                    <br>
                <? } ?>
                <a class="btnLink" target="_blank" href="/route/download/id/<?= $this->route->routeId ?>">
                    <button class="btn btn-primary btn-nopad">
                        <i class="fa fa-download"></i> Download
                    </button>
                </a>

            </div>
            <div class="col-md-6">
                <h3> Route Details </h3>
                <table class="table routeDetailsTable">
                    <tbody>
                    <tr>
                        <td>Start
                        </td>
                        <td><span id="start_point" data-latlng="<?= $this->firstPoint ?>"></span></td>
                    </tr>
                    <tr>
                        <td>End</td>
                        <td><span id="end_point" data-latlng="<?= $this->lastPoint ?>"></span></td>
                    </tr>
                    <tr>
                        <td>Distance</td>
                        <td>NYI</td>
                    </tr>
                    <tr>
                        <td>Petrol Cost</td>
                        <td>NYI</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td></td>
                    </tr>
                    </tbody>
                </table>

                <div>
                    <i>
                        <?= $this->route->description ?>
                    </i>
                </div>
            </div>
        </div>
    </div>

    <div class="col-md-5" id="socialStream">
        <h3 class="title"> Social Stream</h3>

        <div class="shareThisRoute">
            <div class="bold">
                Like this route? Why not share it?
            </div>
            <div class="shareIcons">
                <i class="fa fa-facebook-square"></i>
                <i class="fa fa-twitter-square"></i>
                <i class="fa fa-reddit-square"></i>
                <i class="fa fa-tumblr-square"></i>
                <i class="fa fa-envelope-square"></i>
            </div>
        </div>

        <? if (!(is_null($this->user)) && ($this->user->username != $this->route->owner)) { ?>
            <div class="commentBox">
            <span class="bold">
                Got something to say?
            </span>
                <div class="row">
                    <div class="input-group">
                        <textarea class="form-control custom-control" id="comment-input" rows="2"></textarea>
                        <span class="input-group-addon btn btn-success" id="comment-btn">Comment</span>
                    </div>
                </div>
            </div>
        <? } ?>

        <div class="streamElements" style="">
            <div class="bold">See what others thought:</div>
            <div class="elements">
                <? if (count($this->socialStream) > 0) { ?>
                    <? foreach ($this->socialStream as $element) { ?>
                        <div class="streamElement <?= $element->type ?>">
                            <i class="<?= $element->icon ?>"></i>
                            <? if ($element->type == 'share') { ?>
                                <i class="fa fa-<?= $element->valueString ?>-square"></i>
                            <? } ?>
                            <span class="bold"> <?= $element->username ?> </span>

                            <? if ($element->type === 'comment') { ?>
                                <span class="right commentAction">
                                    <? if (!(is_null($this->user))) { ?>
                                        <? if ($element->username == $this->user->username) { ?>
                                            <i class="fa fa-times"></i>
                                        <? } else { ?>
                                            <i class="fa fa-flag"></i>
                                        <? }
                                    } ?>
                                </span>
                                says: <p> <?= $element->comment ?> </p>
                                <input type="hidden" class="commentId" value="<?= $element->valueId ?>">
                            <? } else if ($element->type === 'rate') { ?>
                                gave this route a rating of
                                <span class="userRatingValue"><?= $element->rating ?></span>
                                <i class="fa fa-star"></i>
                                <? if (!is_null($this->user) && $element->username == $this->user->username) { ?>
                                    <div class="hidden" id="userRating"></div>
                                <? } ?>

                            <? } else { ?>
                                <?= rtrim($element->type, 'e') ?>ed this route
                                <?= ($element->type == 'share' ? ' to ' . ucfirst($element->valueString) : '') ?>
                            <? } ?>
                        </div>
                    <? } ?>
                <? } else { ?>
                    No one has said anything yet! Why not kick off the discussion?
                <? } ?>
            </div>
        </div>
    </div>
</div>