<?/*

Make it so the elements are 400px, or 50% of screen (which ever is bigger);
*/?>

<div class="row">
    <div class="col-xs-12 hero" style="">
        <span style="color:white">
            <div style="padding-bottom:10px; margin-top:20px; font-size:30px">Dear Send Grid.</div> 
            My name is Craig Knott and I am a Computer Science student at the University of Nottingham. Niceway.to is my Master's dissertation project, and will be a service that allows users to collaborate and share scenic routes they have visited, with each other.The idea being that people don't appreciate the world around them enough, and they should take the time to embrace it more. The reason I am using send grid, is because I see you guys at hackathons all the time (I have tons of your stickers!), and know your service to be easy to use, and good at what it does. The reason I need emails on my website is for email confirmations, notifications (someone has commented on your route... etc), and other things like this. The only people I will be emailing, will be the people that have registered with the site, which will be an extremely populate for the next 12 months, and may potentially be higher when the project is complete, at which point I will pay you for more emails!<br>
<br>
            Please let me use your service, and let me know if you have any questions - psyck@nottingham.ac.uk is my academic email address<br>
<br>
            Thanks,<br>
            Craig<br>
<br>
            (I wrote this blurb because this index page is a WIP at the moment and I didn't want you to think I was a spam site)
        </span>

    </div>
</div>
<div class="row">
    <div class="col-xs-12 col-sm-4 section">
        <div class="section-header">
            <i class="fa fa-search section-icon"></i>
            <div class="section-title">Search</div>
        </div>
        <p>
            explanation
        </p>
    </div>
    <div class="col-xs-12 col-sm-4 section"">
        <div class="section-header">
            <i class="fa fa-street-view section-icon"></i>
            <div class="section-title">Explore</div>
        </div>
        <p>
            explanation
        </p>
    </div>
    <div class="col-xs-12 col-sm-4 section">
        <div class="section-header">
            <i class="fa fa-share-square-o section-icon"></i>
            <div class="section-title">Share</div>
        </div>
        <p>
            explanation
        </p>
    </div>
</div>