<?/*

Make it so the elements are 400px, or 50% of screen (which ever is bigger);
*/?>

<div class="row">
    <div class="col-xs-12 hero" style="">
        Some big map / inspirational image
    </div>
</div>
<div class="row">
    <div class="col-xs-12 col-sm-4 section">
        <div class="section-header">
            <i class="fa fa-search section-icon"></i>
            <div class="section-title">Search</div>
        </div>
        <p>
            explanation
        </p>
    </div>
    <div class="col-xs-12 col-sm-4 section"">
        <div class="section-header">
            <i class="fa fa-street-view section-icon"></i>
            <div class="section-title">Explore</div>
        </div>
        <p>
            explanation
        </p>
    </div>
    <div class="col-xs-12 col-sm-4 section">
        <div class="section-header">
            <i class="fa fa-share-square-o section-icon"></i>
            <div class="section-title">Share</div>
        </div>
        <p>
            explanation
        </p>
    </div>
</div>