<div class="row">
    <div class="col-md-3">
        <div class="border-container searchTermContainer">
            <div class="title searchtermsTitle">
                Search Terms
            </div>
            <div class="searchTermBody">
                <form enctype="application/x-www-form-urlencoded" action="" method="post" id="">

                    <label for="start_address">
                        Start And Finish
                    </label>
                    <input type="text" class="form-control" name="start_address" id="start_address" value="<?= $this->startAddress ?>">
                    <input type="text" class="form-control" name="end_address" id="end_address" value="<?= $this->endAddress ?>">

                    <label for="max_distance">
                        Maximum Distance (km)
                    </label>
                    <input type="number" class="form-control" name="max_distance" id="max_distance" value="<?= $this->maxDistance ?>">

                    <input type="button" class="btn btn-success center-block" id="submit_search" value="Search Again">
                </form>
            </div>
        </div>
    </div>

    <div class="col-md-9">
        <h3>
            Your search for routes from <?= $this->startAddress ?> to <?= $this->endAddress ?>
            had <?= count($this->routes) ?> results
        </h3>
        <p>
            Not what you were looking for? Trying being more specific (i.e, St.Ives, Cornwall, instead of just St.Ives)
        </p>
        <? foreach ($this->routes as $route) { ?>
            <? if (!($route->onPage)) { ?>
                <? continue; ?>
            <? } ?>
            <div class="route">
                <h3> <?= $route->name ?> </h3>
                by <?= $route->owner ?>
                <div class="rating" id="ratingContainer">
                    <?= $this->partial('user', 'stars', null, array(
                        'rating' => $route->rating
                    )); ?>
                </div>
                <div>
                    <?= $route->start_address ?> to <?= $route->end_address ?>
                </div>
                <div>
                    <?= $route->description ?>
                </div>
                <div class="stats">
                    <i class="fa fa-comment"></i> <?= $route->comments ?> comments
                    <br>
                    <i class="fa fa-star"></i> <?= $route->ratings ?> ratings
                    <br>
                    <i class="fa fa-share"></i> <?= $route->shares ?> shares
                    <br>
                    <i class="fa fa-download"></i> <?= $route->downloads ?> downloads
                    <br>
                    <i class="fa fa-clone"></i> <?= $route->forks ?> clones
                </div>
            </div>
        <? } ?>
    </div>
</div>

<form enctype="application/x-www-form-urlencoded" action="/route/list" method="post" id="pageForm">
    <input type="hidden" name="start_lat" id="start_lat" value="<?= $this->startLat ?>">
    <input type="hidden" name="start_lng" id="start_lng" value="<?= $this->startLng ?>">
    <input type="hidden" name="end_lat" id="end_lat" value="<?= $this->endLat ?>">
    <input type="hidden" name="end_lng" id="end_lng" value="<?= $this->endLng ?>">
    <input type="hidden" name="formError" id="formError">

    <input type="hidden" name="start_address" id="start_address" value="<?= $this->startAddress ?>">
    <input type="hidden" name="end_address" id="end_address" value="<?= $this->endAddress ?>">
    <input type="hidden" name="page_num" id="page_num" value="<?= $this->pageNum ?>">
    <input type="hidden" name="page_lim" id="page_lim" value="<?= $this->pageLimit ?>">
</form>

<nav>
    <ul class="pagination">
        <li class="prevPage <?= ($this->pageNum == 0) ? 'disabled' : '' ?>">
            <a href="#" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
            </a>
        </li>
        <? for ($i = 0; $i < count($this->routes); $i += $this->pageLimit) { ?>
            <li class="iPage <?= (($i / $this->pageLimit) == $this->pageNum) ? 'active' : '' ?>">
                <a href="#"><?= 1 + ($i / $this->pageLimit) ?></a>
            </li>
        <? } ?>

        <li class="nextPage <?= ((count($this->routes) / $this->pageLimit) == ($this->pageNum + 1)) ? 'disabled' : '' ?>">
            <a href="#" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
            </a>
        </li>
    </ul>
</nav>
