<div class="row">
    <div id="map">

    </div>
</div>

<div class="row">
    <div class="col-md-3">
        <div class="border-container searchTermContainer">
            <div class="title searchtermsTitle">
                Search Terms
            </div>
            <div class="searchTermBody">
                <div class="searchFormContainer">
                    <form enctype="application/x-www-form-urlencoded" action="/route/list" method="post" id="searchForm">
                        <input type="hidden" name="start_lat" id="start_lat_1">
                        <input type="hidden" name="start_lng" id="start_lng_1">
                        <input type="hidden" name="end_lat" id="end_lat_1">
                        <input type="hidden" name="end_lng" id="end_lng_1">
                        <input type="hidden" name="formError" id="formError_1">

                        <label for="start_address_1">
                            Start and End
                        </label>
                        <input type="text" class="form-control" name="start_address" id="start_address_1" value="<?=
                        $this->startAddress ?>">
                        <input type="text" class="form-control" name="end_address" id="end_address_1" value="<?=
                        $this->endAddress ?>">

                        <label for="max_distance">
                            Maximum Distance (km)
                        </label>
                        <input type="number" class="form-control" name="max_dist" id="max_dist" value="<?= $this->maxDistance ?>">

                        <label for="max_distance">
                            Minimum Star Rating
                        </label>
                        <span class="clearBtn">
                            (
                            <span class="inner">
                                <i class="fa fa-times"></i> clear
                            </span>
                            )
                        </span>

                        <div class="row">
                            <div class="clickableRating">
                                <?= $this->partial('user', 'stars', null, array(
                                    'rating'   => $this->minStars,
                                    'showId'   => true,
                                    'addBreak' => true,
                                    'fontSize' => '26px'
                                )); ?>
                            </div>
                        </div>

                        <input type="hidden" class="form-control" name="min_stars" id="min_stars" value="<?= $this->minStars ?>">

                        <div class="searchButton">
                            <button class="btn btn-success" id="submit_addresses">
                                <i class="fa fa-search"></i> Search Again
                            </button>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>

    <div class="col-md-9">
        <h3>
            Your search for routes from <?= $this->startAddress ?>
            <?= $this->endAddress != '' ? 'to ' . $this->endAddress : '' ?>
            had <?= count($this->routes) ?> results
        </h3>
        <p>
            Not what you were looking for? Trying being more specific (i.e, "<i>St.Ives, Cornwall</i>", instead of just
            "<i>St.Ives</i>")
        </p>
        <? $i = 0; ?>
        <? foreach ($this->routes as $route) { ?>
            <? if (!($route->onPage)) { ?>
                <? continue; ?>
            <? } ?>
            <?= $this->partial('route', 'route', null, array(
                'route' => $route,
                'mapId' => 'map_' . $i
            )); ?>
            <? $i++; ?>
        <? } ?>

        <? if (count($this->routes) > $this->pageLimit) { ?>
            <div class="text-center">
                <nav>
                    <ul class="pagination">
                        <li class="prevPage <?= ($this->pageNum == 0) ? 'disabled' : '' ?>">
                            <a href="#" aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                            </a>
                        </li>
                        <? for ($i = 0; $i < count($this->routes); $i += $this->pageLimit) { ?>
                            <li class="iPage <?= (($i / $this->pageLimit) == $this->pageNum) ? 'active' : '' ?>">
                                <a href="#"><?= 1 + ($i / $this->pageLimit) ?></a>
                            </li>
                        <? } ?>

                        <li class="nextPage <?= ((count($this->routes) / $this->pageLimit) == ($this->pageNum + 1)) ? 'disabled' : '' ?>">
                            <a href="#" aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                            </a>
                        </li>
                    </ul>
                </nav>
            </div>
        <? } ?>
    </div>
</div>

<form enctype="application/x-www-form-urlencoded" action="/route/list" method="post" id="pageForm">
    <input type="hidden" name="start_lat" id="start_lat" value="<?= $this->startLat ?>">
    <input type="hidden" name="start_lng" id="start_lng" value="<?= $this->startLng ?>">
    <input type="hidden" name="end_lat" id="end_lat" value="<?= $this->endLat ?>">
    <input type="hidden" name="end_lng" id="end_lng" value="<?= $this->endLng ?>">
    <input type="hidden" name="formError" id="formError">

    <input type="hidden" name="start_address" id="start_address" value="<?= $this->startAddress ?>">
    <input type="hidden" name="end_address" id="end_address" value="<?= $this->endAddress ?>">
    <input type="hidden" name="page_num" id="page_num" value="<?= $this->pageNum ?>">
    <input type="hidden" name="page_lim" id="page_lim" value="<?= $this->pageLimit ?>">
</form>

