<div>
    Hi there,
</div>
<br>
<div>
    Someone just requested a password reset email for Niceway.to be sent to this email address. If this was you,
    please click on the link below (or paste it into your address bar) to begin the password reset process.
</div>
<br>
<div>
    If this wasn't you, someone may be trying to access your account.
</div>
<br>
<div>
    <a href="niceway.to/member/changepassword/hash/<?= $this->hash ?>">
        Click here to change your password
    </a>
</div>
<br>
<div>
    If you cannot click on the link above, simply copy this into your browser url bar:
    niceway.to/member/changepassword/hash/<?= $this->hash ?>
</div>