<div>
    Hi, there!
</div>
<br>
<div>
    A new announcement has been posted on Niceway.to that we thought you might be interested in:
</div>
<br>
<div>
    <i> <?= $this->message ?> </i>
</div>
<br>
<div>
    If you wish to stop receiving these emails, you can disable them in your email settings, found
    <a href="http://niceway.to/user/settings">http://niceway.to/user/settings</a>
</div>