<style>
    .well {
        margin-top: 25%;
    }

    .well .title {
        margin-top: 10px;
        margin-bottom: 20px;
    }

    #login-element {
        text-align: center;
    }

    #login-element input {
        width: 100px;
    }

    .signupBtn {
        width: 100px;
    }

    .orSignup {
        text-align: center;
    }

    .orSignup p {
        margin-top: 0px;
        margin-bottom: 5px;    
    }
    
    .zend_form {
        margin-bottom: 0px;
    }

    dt {
        padding-top: 5px;
    }

    body {
        background-image: url("https://upload.wikimedia.org/wikipedia/commons/8/8e/Highland_scenic_highway.jpg");
        background-size: 100vw 100vh;
        background-repeat: no-repeat;
        overflow: hidden;
    }
</style>
<div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6">
        <div class="well">
            <h2 class="title">Log in to Niceway.to</h2>
            <div class="row">
                <div class="col-md-1">
                </div>
                <div class="col-md-10">
                    <?= $this->loginForm; ?>
                    <div class="orSignup">
                        <p>or</p>
                        <input type="button" class="btn btn-primary signupBtn" value="Sign Up">    
                    </div>
                </div>
                <div class="col-md-1">
                </div>                
            </div>
        </div>
    </div>
    <div class="col-md-3"></div>
</div>