<style>
    .margin_b_15 {
        margin-bottom:15px;
    }

    .margin_t_15 {
        margin-top:15px;
    }
</style>

<div class="row margin_t_15">
    <div class="col-md-3">
        <div class="list-group">
          <a href="/nicewaytomockups/mydetails" class="list-group-item">
            <h4 class="list-group-item-heading">My Details</h4>
            <p class="list-group-item-text">View and edit your account information and password</p>
          </a>
            <a href="/nicewaytomockups/myroutes" class="list-group-item active">
            <h4 class="list-group-item-heading">My Routes</h4>
            <p class="list-group-item-text">View and edit your submitted routes</p>
          </a>
           <a href="/nicewaytomockups/admin" class="list-group-item">
            <h4 class="list-group-item-heading">Admin</h4>
            <p class="list-group-item-text">Access administrative tools to manage the site</p>
          </a>
        </div>
    </div>
    <div class="col-md-8">
        <div class="panel panel-primary">
          <div class="panel-heading">
            <h3 class="panel-title">My Routes</h3>
          </div>
          <div class="panel-body">
               <div class="table-responsive">
                <table class="table table-striped">
                    <thead>
                        <th>Name</th>
                        <th>Start</th>
                        <th>End</th>
                        <th>Privacy [?]</th>
                        <th>Manage</th>
                    </thead>
                    <tbody>
                        <tr>
                            <td>Route A</td>
                            <td>Place 1</td>
                            <td>Place 2</td>
                            <td>Public</td>
                            <td>
                                <span class="glyphicon glyphicon-pencil" style="font-size: 18px"></span>
                                <span class="glyphicon glyphicon-download-alt" style="font-size: 18px"></span>
                                <span class="glyphicon glyphicon-remove" style="font-size: 18px"></span>
                            </td>
                        </tr>
                        <tr>
                            <td>Route B</td>
                            <td>Place 3</td>
                            <td>Place 4</td>
                            <td>Public</td>
                            <td>
                                <span class="glyphicon glyphicon-pencil" style="font-size: 18px"></span>
                                <span class="glyphicon glyphicon-download-alt" style="font-size: 18px"></span>
                                <span class="glyphicon glyphicon-remove" style="font-size: 18px"></span>
                            </td>
                        </tr>
                        <tr>
                            <td>Route C</td>
                            <td>Place 5</td>
                            <td>Place 6</td>
                            <td>Private</td>
                            <td>
                                <span class="glyphicon glyphicon-pencil" style="font-size: 18px"></span>
                                <span class="glyphicon glyphicon-download-alt" style="font-size: 18px"></span>
                                <span class="glyphicon glyphicon-remove" style="font-size: 18px"></span>
                            </td>
                        </tr>
                    </tbody>
                </table>
                <div class="col-md-12">
                    <input type="submit" class="btn btn-success right" value="Add New"/>
                </div>
            </div>

          </div>
        </div>
    </div>
</div>
 


