<div style="padding-left:10px">
    <div><a href="/nicewaytomockups/login">Log in page</a></div>
    <div><a href="/nicewaytomockups/signup">Sign up Page</a></div>
    <div><a href="/nicewaytomockups/mydetails">My Details Page</a></div>
    <div><a href="/nicewaytomockups/myroutes">My Routes Page</a></div>
    <div><a href="/nicewaytomockups/admin">Admin Page</a></div>
    <div><a href="/nicewaytomockups/routeindex">Route Discovery Page</a></div>
    <div><a href="/nicewaytomockups/routelisting">Route Listing Page</a></div>
    <div><a href="/nicewaytomockups/routedetail">Route Detail Page</a></div>
    <div><a href="/nicewaytomockups/routecreate">Route Creation Page</a></div>
</div>
