<style>
    body {
        background-image: url("/images/gmaps-with-points.png");
        background-size: 1920px 1080px;
        background-repeat: no-repeat;
        background-position: -400px -100px;
        overflow: hidden;
    }

    .routeDetailPanel {
        background-color: #FFFFFF;
    }

    .tableHeader {
        font-size: 24px;
        padding-top:10px;
        text-align:center;
    }
    .lrgText {
        font-size:16px;
    }
</style>

<div class="row">
    <div class="col-md-3">
        <div class="routeDetailPanel">
            <div class="tableHeaderContainer">
                <h2 class="tableHeader">Your Route</h2>
            </div>
            <table class="table table-striped">
                <tr>
                    <td> 
                        <span class="glyphicon glyphicon-map-marker" style="font-size:15px"></span>
                        <span class="lrgText"> 1. (-64, 11) </span>
                        <span class="glyphicon glyphicon-remove right" style="font-size:15px"></span>
                    </td>
                </tr>
                <tr>
                    <td> 
                        <span class="glyphicon glyphicon-map-marker" style="font-size:15px"></span>
                        <span class="lrgText"> 1. (-64, 11) </span>
                        <span class="glyphicon glyphicon-remove right" style="font-size:15px"></span>
                    </td>
                </tr>
                <tr>
                    <td> 
                        <span class="glyphicon glyphicon-map-marker" style="font-size:15px"></span>
                        <span class="lrgText"> 1. (-64, 11) </span>
                        <span class="glyphicon glyphicon-remove right" style="font-size:15px"></span>
                    </td>
                </tr>
                <tr>
                    <td> 
                        <span class="glyphicon glyphicon-map-marker" style="font-size:15px"></span>
                        <span class="lrgText"> 1. (-64, 11) </span>
                        <span class="glyphicon glyphicon-remove right" style="font-size:15px"></span>
                    </td>
                </tr>
                <tr>
                    <td> 
                        <span class="glyphicon glyphicon-map-marker" style="font-size:15px"></span>
                        <span class="lrgText"> 1. (-64, 11) </span>
                        <span class="glyphicon glyphicon-remove right" style="font-size:15px"></span>
                    </td>
                </tr>
                <tr>
                    <td  style="background-color:#C2D59A !important; text-align:center; color:white"> 
                          Submit
                    </td>
                </tr>                
            </table>
        </div>
    </div>
    <div class="col-md-6">
    </div>
    <div class="col-md-3">
        <table class="table" style="margin-top:20px; background-color:white; font-size:16px;">
            <tr>
                <td> 
                    <p style="padding: 10px;margin: 0;">Welcome to the route creation tool! To get started, click on the map to add a point!</p>
                </td>
            </tr>
            <tr>
                <td style="background-color:#94B2D6 !important; text-align:center; color:white"> 
                      Go it, thanks!
                </td>
            </tr>
        </table>
    </div>    
</div>

