
<div class="row">
    <div class="col-md-3">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title">Your Search Terms
                </h3>
            </div>
            <div class="panel-body">
                <label> Start and Finish</label>
                <input type="text" class="form-control" value="Queen's Medical Centre">
                <input type="text" style="margin-top: 5px;" class="form-control" value="Wollaton Road">
  
                <label style="margin-top: 15px;"> Price Range (£)</label><br>
                <input type="number" class="form-control" style="width:49%; float:left; margin-right:2%" value="0">
                <input type="number" class="form-control" style="width:49%; float:left" value="10">

                <label style="margin-top: 15px;"> Distance Range (KM)</label><br>
                <input type="number" class="form-control" style="width:49%; float:left; margin-right:2%" value="0">
                <input type="number" class="form-control" style="width:49%; float:left" value="10">

                <label style="margin-top: 15px;"> Minimum Rating </label><br>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star-o"></i>
                <i class="fa fa-star-o"></i>  


                <div style="text-align:center; margin-top:15px">
                    <input type="submit" class="btn btn-success" value="Search Again">
                </div>
                
            </div>
        </div>
    </div>

    <div class="col-md-9">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title">Your Search Results
                </h3>
            </div>
            <div class="panel-body">
                <div class="row" style="padding-top:10px; padding-bottom:10px; border-bottom:1px solid #ccc">
                    <div class="col-md-3">
                        <img style="width:128px; height:128px" src="https://maps.googleapis.com/maps/api/staticmap?center=52.954785,-1.193291%7C52.955664&zoom=14&size=320x320&maptype=roadmap&markers=color:blue%7Clabel:A%7C52.944468,%20-1.190073&markers=color:blue%7Clabel:B%7C52.954785,%20-1.193291&markers=color:blue%7Clabel:C%7C52.955664,%20-1.175653&path=color:blue%7Cweight:5%7C52.944468,-1.190073%7C52.954785,-1.193291%7C52.955664,-1.175653&key=AIzaSyBdGDXYIc0fK_SGoImxqOozcXkNwyPqofI">
                    </div>  

                    <div class="col-md-9">
                        <div class="row">
                            <div class="col-md-12">
                                <div style="font-size:24px">Nottingham 3 Point Adventure</div>                        
                            </div>
                            <div class="col-md-12">
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star-o"></i>
                                <i class="fa fa-star-o"></i>             
                            </div>                         
                            <div class="col-md-12">
                                <div style="">Queen's Medical Center to Wollaton Road</div>                        
                            </div>                    
                            <div class="col-md-12">
                                <div style="">Distance: 10KM (5KM Higher than quickest route)</div>                        
                            </div>                                                    
                            <div class="col-md-12">
                                <div style="">Est. Petrol: £10</div>                        
                            </div>                                
                        </div>
                        
                    </div>
                </div>
                
                <div class="row" style="padding-top:10px; padding-bottom:10px; border-bottom:1px solid #ccc">
                    <div class="col-md-3">
                        <img style="width:128px; height:128px" src="https://maps.googleapis.com/maps/api/staticmap?center=52.954785,-1.193291%7C52.955664&zoom=14&size=320x320&maptype=roadmap&markers=color:blue%7Clabel:A%7C52.944468,%20-1.190073&markers=color:blue%7Clabel:B%7C52.954785,%20-1.193291&markers=color:blue%7Clabel:C%7C52.955664,%20-1.175653&path=color:blue%7Cweight:5%7C52.944468,-1.190073%7C52.954785,-1.193291%7C52.955664,-1.175653&key=AIzaSyBdGDXYIc0fK_SGoImxqOozcXkNwyPqofI">
                    </div>  

                    <div class="col-md-9">
                        <div class="row">
                            <div class="col-md-12">
                                <div style="font-size:24px">Nottingham 3 Point Adventure</div>                        
                            </div>
                            <div class="col-md-12">
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star-o"></i>
                                <i class="fa fa-star-o"></i>             
                            </div>                         
                            <div class="col-md-12">
                                <div style="">Queen's Medical Center to Wollaton Road</div>                        
                            </div>                    
                            <div class="col-md-12">
                                <div style="">Distance: 10KM (5KM Higher than quickest route)</div>                        
                            </div>                                                    
                            <div class="col-md-12">
                                <div style="">Est. Petrol: £10</div>                        
                            </div>                                
                        </div>
                        
                    </div>
                </div>

                <div class="row" style="padding-top:10px; padding-bottom:10px;">
                    <div class="col-md-3">
                        <img style="width:128px; height:128px" src="https://maps.googleapis.com/maps/api/staticmap?center=52.954785,-1.193291%7C52.955664&zoom=14&size=320x320&maptype=roadmap&markers=color:blue%7Clabel:A%7C52.944468,%20-1.190073&markers=color:blue%7Clabel:B%7C52.954785,%20-1.193291&markers=color:blue%7Clabel:C%7C52.955664,%20-1.175653&path=color:blue%7Cweight:5%7C52.944468,-1.190073%7C52.954785,-1.193291%7C52.955664,-1.175653&key=AIzaSyBdGDXYIc0fK_SGoImxqOozcXkNwyPqofI">
                    </div>  

                    <div class="col-md-9">
                        <div class="row">
                            <div class="col-md-12">
                                <div style="font-size:24px">Nottingham 3 Point Adventure</div>                        
                            </div>
                            <div class="col-md-12">
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star-o"></i>
                                <i class="fa fa-star-o"></i>             
                            </div>                         
                            <div class="col-md-12">
                                <div style="">Queen's Medical Center to Wollaton Road</div>                        
                            </div>                    
                            <div class="col-md-12">
                                <div style="">Distance: 10KM (5KM Higher than quickest route)</div>                        
                            </div>                                                    
                            <div class="col-md-12">
                                <div style="">Est. Petrol: £10</div>                        
                            </div>                                
                        </div>
                        
                    </div>
                </div>  
            </div>
        </div>
    </div>
</div>

