<style>
    .well {
        margin-top: 15%;
    }

    .well .title {
        margin-top: 10px;
        margin-bottom: 20px;
    }

    #signup-element {
        text-align: center;
    }

    #signup-element input {
        width: 100px;
    }

    body {
        background-image: url("http://www.blackchickontour.com/wp-content/uploads/2012/01/The-Big-Island-Scenic-Lookout.jpg");
        background-size: 100vw 100vh;
        background-repeat: no-repeat;
        overflow: hidden;
    }

    dt {
        padding-top: 2px;
        font-weight:0px;
        line-height: 5px;
    }


</style>
<div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6">
        <div class="well">
            <h2 class="title">Sign up to Niceway.to</h2>
            <div class="row">
                <div class="col-md-1">
                </div>
                <div class="col-md-10">
                    <?= $this->signupForm ?>
                </div>
                <div class="col-md-1">
                </div>                
            </div>            
            
        </div>
    </div>
    <div class="col-md-3"></div>
</div>
