<input type="hidden" id="currentPeriod" value="<?= $this->periodId ?>">
<input type="hidden" id="cpSd" value="<?= $this->start_date ?>">
<input type="hidden" id="cpEd" value="<?= $this->end_date ?>">
<input type="hidden" id="examsCount" value="<?= $this->examsCount ?>">

<div class="row">
    <div class="col-md-2">
        <a href="#timer-popup" class="popup-trigger">
            <button type="button" class="btn btn-default">
                <span class="glyphicon glyphicon-time"></span>
            </button>
        </a>
        <a href="#stats-popup" class="popup-trigger">
            <button type="button" class="btn btn-default">
                <span class="glyphicon glyphicon-stats"></span>
            </button>
        </a>

        <div id="timer-popup" class="white-popup-block zoom-anim-dialog mfp-hide">
            <div id="displayTimer">
                <span id="d_hr">00</span>:<span id="d_min">00</span>:<span id="d_sec">00</span>
            </div>

            <input type="button" class="btn btn-success" value="Start" id="startBtn">
            <input type="button" class="btn btn-danger" value="Stop" id="stopBtn" disabled>
            <input type="button" class="btn btn-primary" value="Reset" id="resetBtn">
        </div>
        <div id="stats-popup" class="white-popup-block zoom-anim-dialog mfp-hide">
            <h3>
                Revision Statistics
                <a href="#" data-toggle="tooltip" class="blackText" data-original-title="Accurate at time of page load">
                    [?]
                </a>
            </h3>

            <div class="table-responsive">
                <table class="table">
                    <tbody>
                        <? foreach ($this->stats as $stat) { ?>
                            <tr>
                                <td> <?= $stat->name ?> </td>
                                <td> <?= $stat->value ?> </td>
                            </tr>
                        <? } ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <div class="col-md-8">
        <div id="soonBanner"></div>
    </div>

    <div class="col-md-2">
        <div class="right b_margin_5">
            <b> Select Revision Period </b>
            <select id="revisionPeriodSelect" class="input-large form-control">
                <? foreach ($this->periods as $period) { ?>
                    <option id="<?= 'pid_' . $period->id ?>"> <?= $period->name ?> </option>
                <? } ?>
            </select>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-4 <?= ($this->examsCount == 0) ? 'hidden' : '' ?>">
        <div class="panel panel-default">
            <div class="panel-heading">Revision Progress</div>
            <div class="panel-body">
                <table class="table table-condensed table-striped" id="revision_progress_table">
                </table>
            </div>
        </div>
    </div>

    <div class="col-md-8 <?= ($this->examsCount == 0) ? 'hidden' : '' ?>">
        <div class="panel panel-default">
            <div class="panel-heading">Progress Chart</div>
            <div class="panel-body">
                <img src="/images/global/loading.gif" class="loading" id="revChart_loading">
                <div id="revision_progress_chart_div" style="width:100%"></div>
            </div>
        </div>
    </div>

    <div class="col-md-<?= ($this->examsCount == 0) ? '12' : '8' ?>">
        <div class="panel panel-default">
            <div class="panel-heading">Exam Timetable</div>
            <div class="panel-body">
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                        <tr>
                            <th> Module</th>
                            <th> Worth</th>
                            <th> Location</th>
                            <th> Date</th>
                            <th> Time</th>
                            <th> Length</th>
                            <th> Seat</th>
                            <th> Manage</th>
                        </tr>
                        </thead>
                        <tbody id="examsTbody">
                        </tbody>
                    </table>
                </div>
                <div class="row hidden" id="addExamInput">
                    <div class="col-md-4 col-sm-6">
                        <label> Module Name (max 3 chars) </label>
                        <div class="form-group" id="moduleInputWrapper">
                            <input type="text" id="moduleInput" class="form-control" placeholder="Module Name">
                        </div>
                    </div>

                    <div class="col-md-4 col-sm-6">
                        <label> Exam Worth</label>
                        <div class="form-group" id="worthInputWrapper">
                            <input type="number" id="worthInput" class="form-control" placeholder="% of module">
                        </div>
                    </div>

                    <div class="col-md-4 col-sm-6">
                        <label> Location </label>
                        <div class="form-group" id="locationInputWrapper">
                            <input type="text" id="locationInput" class="form-control" placeholder="Location of exam">
                        </div>
                    </div>

                    <div class="col-md-4 col-sm-6">
                        <label> Date </label>
                        <div class="form-group" id="dateInputWrapper">
                            <input type="text" id="dateInput" class="form-control" placeholder="Date of exam">
                        </div>
                    </div>

                    <div class="col-md-4 col-sm-6">
                        <label> Time </label>
                        <div class="form-group" id="timeInputWrapper">
                            <input id="timeInput" type="text" class="form-control ui-timepicker-input" data-scroll-default="9:00am" autocomplete="off" placeholder="Time of exam">
                        </div>
                    </div>

                    <div class="col-md-4 col-sm-6">
                        <label> Length </label>
                        <div class="form-group" id="lengthInputWrapper">
                            <input type="number" id="lengthInput" class="form-control" placeholder="Length in hours">
                        </div>
                    </div>

                    <div class="col-md-4 col-sm-6">
                        <label> Seat </label>
                        <div class="form-group" id="seatInputWrapper">
                            <input type="text" id="seatInput" class="form-control" placeholder="Seat Number">
                        </div>
                    </div>

                </div>
                <div class="row">
                    <div class="col-md-12">
                        <input type="button" class="btn btn-danger hidden" value="Delete Exam" id="deleteExam">
                        <input type="button" class="btn btn-success right hidden" value="Update" id="updateExam">
                        <input type="button" class="btn btn-success right" value="Add Exam" id="addExam">
                        <input type="button" class="btn btn-danger right hidden r_margin_5" value="Cancel" id="closeExamBox">
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>