<div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">
        <div class="well">
            <h2>Login</h2>
            <? if (!is_null($this->errorMessage)) { ?>
                <div class="alert alert-danger" role="alert">
                    <?= $this->errorMessage; ?>
                </div>
            <? } ?>
            <?= $this->loginForm; ?>
        </div>
    </div>
    <div class="col-md-2"></div>
</div>