<a href="/admin/locksite/lock/<?= !($this->siteAdmin->is_locked) ?>">
    <? if ($this->siteAdmin->is_locked) { ?>
        <button class="btn btn-success btn-nopad">
            <i class="fa fa-unlock"></i> Unlock Site
        </button>
    <? } else { ?>
        <button class="btn btn-danger btn-nopad">
            <i class="fa fa-lock"></i> Lock Site
        </button>
    <? } ?>
</a>
