<div class="row margin_b_20 margin_t_15">
    <div class="col-sm-1 col-md-1"></div>
    <div class="col-sm-10 col-md-10">
        <div class="border-container">
            <div class="title unresolvedTitle">
                Unresolved Reports
            </div>
            <div class="row">
                <table class="table">
                    <thead>
                        <tr>
                            <th class="col-md-1"> By </th>
                            <th class="col-md-1"> When? </th>
                            <th class="col-md-4"> Reason </th>
                            <th class="col-md-4"> Reported Content </th>
                            <th class="col-md-2"> Actions </th>
                        </tr>
                    </thead>
                    <tbody id="reportsTable">
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="col-sm-1 col-md-2"></div>
</div>