<div class="row">
    <div class="col-md-12">
        Please enter as many fields as possible. Those marked with
        an asterisk are mandatory and the account cannot be
        created without them.
    </div>
</div>
<br>
<div class="row">
    <div class="col-md-6">
        <label> Username <span class="req">*</span></label>
        <div class="form-group" id="usernameInputWrapper">
            <input type="text" id="usernameInput"
                   class="form-control" placeholder="Account user name">
        </div>
    </div>
    <div class="col-md-6">
        <label> Email Address </label>
        <div class="form-group" id="emailInputWrapper">
            <input type="text" id="emailInput"
                   class="form-control" placeholder="Contact email address">
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-6">
        <label> First Name</label>
        <div class="form-group" id="fnameInputWrapper">
            <input type="text" id="fnameInput"
                   class="form-control" placeholder="First name">
        </div>
    </div>
    <div class="col-md-6">
        <label> Last Name</label>
        <div class="form-group" id="lnameInputWrapper">
            <input type="text" id="lnameInput"
                   class="form-control" placeholder="Last Name">
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <input id="createAccount" type="submit" class="btn btn-success btn-right" value="Create"/>
    </div>
</div>