<div class="row">
    <div class="col-md-12">
        <div class="sirenSubsection">
            <div class="panel-heading">
                Add New Siren
            </div>
            <div class="form-group">
                <div class="row">
                    <div class="col-md-9">
                        <label> Message </label>
                        <div class="form-group" id="messageInputWrapper">
                            <input type="text" id="messageInput" class="form-control" placeholder="Message to display">
                        </div>
                    </div>
                    <div class="col-md-3">
                        <label> Application </label>
                        <div class="form-group" id="appInputWrapper">
                            <select id="appInput" class="form-control">
                                <? foreach ($this->appNames as $app) { ?>
                                    <option> <?= $app->url ?> </option>
                                <? } ?>
                            </select>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <input id="addSiren" type="submit" class="btn btn-success btn-right" value="Add"/>
                    </div>
                </div>
            </div>
        </div>
        <hr>
        <div class="sirenSubsection">
            <div class="panel-heading">
                Current Sirens
            </div>
            <? if (count($this->activeSirens) > 0) { ?>
                <table class="table table-striped">
                    <? foreach ($this->activeSirens as $siren) { ?>
                        <tr>
                            <td> <?= $siren->message ?> </td>
                            <td>
                                <a href="<?= $siren->pk_siren_id ?>" class="deactivateSiren">
                                    <button class="btn btn-danger">Deactivate</button>
                                </a>
                            </td>
                            <td><?= $siren->affected_app ?></td>
                        </tr>
                    <? } ?>
                </table>
            <? } else { ?>
                <p> No active sirens (That's a good thing!) </p>
            <? } ?>
        </div>
        <hr>
        <div class="sirenSubsection">
            <div class="panel-heading">
                Past Sirens
            </div>
            <? if (count($this->pastSirens) > 0) { ?>
                <table class="table table-striped">
                    <? foreach ($this->pastSirens as $siren) { ?>
                        <tr>
                            <td><?= $siren->message ?></td>
                            <td>
                                <a href="<?= $siren->pk_siren_id ?>" class="reactivateSiren">
                                    <button class="btn btn-success">Reactivate</button>
                                </a>
                            </td>
                            <td><?= $siren->affected_app ?></td>
                        </tr>
                    <? } ?>
                </table>
            <? } else { ?>
                <p> None added yet! </p>
            <? } ?>
        </div>
    </div>
</div>