<input type="hidden" id="lsfuVal" value="<?= (!is_null($this->lsfu)) ? $this->lsfu : '' ?>">

<div class="row">
    <div class="col-md-12">
        <label> Enter User Id </label>
        <div class="form-group" id="useridInputWrapper">
            <input type="text" id="userid" class="form-control" placeholder="User Id"
                   value="<?= (!is_null($this->lsfu)) ? $this->lsfu : '' ?>">
        </div>
    </div>
    <div class="col-md-12">
        <input type="button" class="btn btn-primary btn-right" id="loadSuppressions" value="Load Suppressions">
    </div>
</div>
<div class="row hidden" id="errorDisplay">
    <hr>
    <div class="alert alert-danger" role="alert">
        <span class="sr-only">Error:</span>
        No user found with that ID
    </div>
</div>
<div class="row hidden" id="suppressionDisplay">
    <hr>
    <div class="row">
        <div class="col-md-12">
            <h4>User Details </h4>
            <table class="table table-condensed table-striped" id="suppression_userInfoDisplayTable">
                <thead>
                <tr>
                    <th>User ID</th>
                    <th>Username</th>
                    <th>Name</th>
                </tr>
                </thead>
                <tbody id="suppression_userInfoDisplayTableBody"></tbody>
            </table>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <h4>
                Please tick the apps you wish to suppress
                <span class="label label-success hidden" id="confirmSave">
                    Saved!
                </span>
            </h4>
        </div>
        <div id="suppressionsCheckboxContainer"></div>
        <div class="col-md-12">
            <input type="button" class="btn btn-success btn-right" id="saveSuppressions" value="Save Suppressions">
        </div>
    </div>
</div>

