<input type="hidden" id="settings_year" value="<?= $this->settings->course_length ?>">
<input type="hidden" id="settings_tab" value="<?= $this->settings->default_tab ?>">

<div class="row">
    <div class="col-md-12" id="mainContainer">
        <div role="tabpanel">
            <ul class="nav nav-tabs" role="tablist">
                <li role="presentation">
                    <a href="#summary" id="summaryTabNav" aria-controls="home" role="tab" data-toggle="tab">
                        Summary
                    </a>
                </li>
                <? for ($i = 1; $i <= $this->settings->course_length; $i++) { ?>
                    <li role="presentation" class="<?= ($i == $this->settings->default_tab) ? 'active' : '' ?>">
                        <a href="#year<?= $i ?>" aria-controls="home" role="tab" data-toggle="tab">
                            Year <?= $i ?>
                        </a>
                    </li>
                <? } ?>
                <li role="presentation" class="noNavTabFocus pull-right">
                    <a id="addModuleTab" href="#addModuleModal" class="noNavTabFocus popup-trigger" role="tab">
                        <span class="glyphicon glyphicon-plus glyphicon-14"></span> Add Module
                    </a>
                </li>
            </ul>
            <div class="tab-content">
                <div role="tabpanel" class="tab-pane" id="summary">
                    <div class="row">
                        <div class="col-md-9">
                            <div class="panel panel-default">
                                <div class="panel-heading text-center">
                                    Distribution of Module Marks
                                </div>
                                <div class="panel-body">
                                    <img src="/images/global/loading.gif" class="loading" id="mrh_loading">
                                    <div id="moduleResultsHistogramContainer">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="panel panel-default">
                                <div class="panel-heading text-center">
                                    Degree Classification
                                </div>
                                <div class="panel-body degreeResultsContainer">
                                    <div class="degreeMark text-center">
                                        <? $totalGrade = 0; ?>
                                        <? foreach ($this->years as $year) { ?>
                                            <? $totalGrade += $year['wGrade'] ?>
                                        <? } ?>
                                        <?= number_format($totalGrade, 2) ?>%
                                    </div>
                                    <div class="degreeResult text-center">
                                        <?= getDegreeClassification($totalGrade) ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <? foreach ($this->years as $id => $year) { ?>
                            <?= $this->partial(
                                'grades',
                                'year',
                                array(
                                    'width'      => ($this->settings->course_length >= 4) ? '3' : '4',
                                    'semesters'  => $year['semesters'],
                                    'weight'     => $year['credits'],
                                    'grade'      => $year['yearGrade'],
                                    'wGrade'     => $year['wGrade'],
                                    'yearNumber' => $id
                                )
                            ); ?>
                        <? } ?>
                    </div>
                </div>
                <? for ($i = 1; $i <= $this->settings->course_length; $i++) { ?>
                    <div role="tabpanel" id="year<?= $i ?>"
                         class="tab-pane<?= ($i == $this->settings->default_tab) ? ' active' : '' ?>">
                        <div class="row">
                            <? foreach ($this->years[$i]['semesters'] as $semester => $modules) { ?>
                                <div class="col-md-4 semester">
                                    <div class="semesterName">
                                        <?= $semester ?>
                                    </div>
                                    <div class="semesterModules">
                                        <? foreach ($modules as $module) { ?>
                                            <?= $this->partial(
                                                'grades',
                                                'module',
                                                array (
                                                    'module'       => $module,
                                                    'courseLength' => $this->settings->course_length
                                                )
                                            ); ?>
                                        <? } ?>
                                    </div>
                                </div>
                            <? } ?>
                        </div>
                    </div>
                <? } ?>
            </div>
        </div>
    </div>
</div>

<!-- Modals -->
<div id="addModuleModal" class="white-popup-block zoom-anim-dialog mfp-hide">
    <div class="moduleForm">
        <h3 class="text-center">Add New Module</h3>

        <div class="form-group row">
            <div class="col-sm-12">
                <label> Module Name </label>
                <input type="text" placeholder="Robotics" class="form-control" id="inputModuleName"/>
            </div>

            <div class="col-sm-6">
                <label> Code </label>
                <input type="text" placeholder="G53ARS" class="form-control" id="inputModuleCode"/>
            </div>

            <div class="col-sm-6">
                <label> Weight </label>
                <input type="number" placeholder="10" class="form-control" id="inputModuleCredits"/>
            </div>

            <div class="col-sm-6">
                <label> Year </label>
                <select class="form-control" id="inputModuleYear">
                    <? for ($i = 1; $i <= $this->settings->course_length; $i++) { ?>
                        <option value="<?= $i ?>"> Year <?= $i ?> </option>
                    <? } ?>
                </select>
            </div>

            <div class="col-sm-6">
                <label> Semester </label>
                <select class="form-control" id="inputModuleSemester">
                    <option value="0"> Full Year</option>
                    <option value="1"> Autumn</option>
                    <option value="2"> Spring</option>
                </select>
            </div>

            <div class="col-sm-12">
                <input type="button" value="Add" id="newModuleSubmitButton" class="form-control btn btn-primary newModuleSubmit"/>
            </div>
        </div>
    </div>
</div>

<div id="deletionModal" class="white-popup-block zoom-anim-dialog mfp-hide">
    <div class="content text-center">
        <div class="text">
            Are you sure you wish to delete?
        </div>
        <div class="buttons">
            <button class="btn btn-danger">Delete</button>
            <button class="btn btn-primary">Cancel</button>
        </div>
    </div>
</div>

<div id="addAssessmentModal" class="white-popup-block zoom-anim-dialog mfp-hide">
    <div class="assessmentForm">
        <h3 class="text-center">Add New Assessment</h3>

        <div class="form-group row">
            <div class="col-sm-12">
                <label> Name </label>
                <input type="text" placeholder="Coursework 1" class="form-control" id="inputAssessmentName"/>
            </div>

            <div class="col-sm-6">
                <label> Weight </label>
                <input type="number" placeholder="20" class="form-control" id="inputAssessmentWeight"/>
            </div>

            <div class="col-sm-6">
                <label> Mark </label>
                <input type="number" placeholder="70" class="form-control" id="inputAssessmentMark"/>
            </div>

            <div class="col-sm-12">
                <input type="button" value="Add" id="newAssessmentSubmitButton" class="form-control btn btn-primary newModuleSubmit"/>
            </div>
        </div>
    </div>
</div>

<?
    function getDegreeClassification($mark) {
        if ($mark < 40) {
            return 'Fail';
        } else if ($mark < 50) {
            return 'Third Class';
        } else if ($mark < 60) {
            return 'Lower Second Class';
        } else if ($mark < 70) {
            return 'Upper Second Class';
        } else  {
            return 'First Class';
        }
    }
?>