<input type="hidden" id="emailConfirmed" value="<?= $this->emailConf ?>">
<input type="hidden" id="notConfirmedEmail" value="<?= $this->nce ?>">

<div class="row">
    <div class="col-sm-1 col-md-2"></div>
    <div class="col-sm-10 col-md-8">
        <div class="border-container">
            <div class="row">
                <div class="col-md-4">
                    <?= $this->partial('user', 'profile_picture', null, array(
                        'skins'         => $this->userSkins,
                        'maxScreenSize' => 1636
                    )); ?>
                </div>
                <div class="col-md-8">
                    <div class="user-detail-list">
                        <div class="row username">
                            <div class="col-sm-12">
                                <?= $this->displayedUser->username ?>
                            </div>
                            <div class="col-sm-12 text-left stars-align">
                                <?= $this->partial('user', 'stars', null, array(
                                    'rating' => $this->displayedUser->stats->ratingAverage
                                )) ?>
                            </div>
                        </div>

                        <? if (!is_null($this->displayedUser->fname)) { ?>
                            <div class="name"><i class="fa fa-user"></i>
                                <?= $this->displayedUser->fname ?> <?= $this->displayedUser->lname ?> </div>
                        <? } ?>

                        <? if (!is_null($this->displayedUser->age)) { ?>
                            <div class="age"><i class="fa fa-calendar"></i>
                                <? $birthDate = date("m/d/Y", strtotime($this->displayedUser->age)); ?>
                                <? $birthDate = explode("/", $birthDate); ?>
                                <?= $age = (date("md", date("U", mktime(0, 0, 0, $birthDate[0], $birthDate[1], $birthDate[2]))) > date("md")
                                    ? ((date("Y") - $birthDate[2]) - 1)
                                    : (date("Y") - $birthDate[2])); ?> years old
                            </div>
                        <? } ?>

                        <? if ($this->viewingOwnProfile) { ?>
                            <div class="email">
                                <i class="fa fa-envelope"></i>
                                <?= $this->displayedUser->email ?>

                                <? if ($this->displayedUser->isConfirmed) { ?>
                                    (<i class="fa fa-check"></i> Confirmed)
                                <? } else { ?>
                                    (<i class="fa fa-exclamation-circle"></i> Not Confirmed)
                                <? } ?>
                            </div>
                        <? } ?>

                        <? if (!is_null($this->displayedUser->location)) { ?>
                            <div class="location">
                                <i class="fa fa-globe"></i>
                                <?= $this->displayedUser->location ?>
                            </div>
                        <? } ?>

                        <div class="joined">
                            <i class="fa fa-clock-o"></i>
                            <?= 'Joined ' . date("d/m/y", strtotime($this->displayedUser->datetimeCreated)) ?>
                            (<?= $this->displayedUser->stats->accountAge . ' days old' ?>)
                        </div>

                        <br>
                        <i>
                            <?= (!is_null($this->displayedUser->bio))
                                ? "\"" . $this->displayedUser->bio . "\"" : "No bio" ?>
                        </i>

                        <div class="border-container">
                            <div class="title yourStatsTitle">
                                <?= $this->viewingOwnProfile ? 'Your' : 'User' ?> Stats
                            </div>
                            <div class="user-stats">
                                <div class="routes-stats">
                                    <i class="fa fa-map-marker"></i>
                                    <?= $this->displayedUser->stats->routeCount ?> routes submitted
                                </div>
                                <div class="comments-stats">
                                    <i class="fa fa-comment"></i>
                                    <?= $this->displayedUser->stats->commentsGiven ?> comments posted
                                    <br>
                                    <i class="fa fa-comments"></i>
                                    <?= $this->displayedUser->stats->commentsReceived ?> comments received
                                </div>
                                <div class="ratings-stats">
                                    <i class="fa fa-star"></i>
                                    <?= $this->displayedUser->stats->ratingsGiven ?> ratings given
                                    <br>
                                    <i class="fa fa-star-o"></i>
                                    <?= $this->displayedUser->stats->ratingsReceived ?> ratings received
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-2"></div>
</div>

<div class="row margin_b_20">
    <div class="col-sm-1 col-md-2"></div>
    <div class="col-sm-10 col-md-8">
        <div class="border-container">
            <div class="title routesTitle">
                Routes
            </div>
            <div class="row">
                <? if (count($this->routes) > 0) { ?>
                    <div id="no-more-tables">
                        <table class="col-md-12 table table-striped table-condensed cf">
                            <thead class="cf">
                            <tr>
                                <th>Name</th>
                                <th class="numeric">Points</th>
                                <? if ($this->viewingOwnProfile) { ?>
                                    <th>Privacy</th>
                                <? } ?>
                                <th>Created</th>
                                <th class="numeric nmth-after"><i class="fa fa-comment"></i></th>
                                <th class="numeric nmth-after"><i class="fa fa-clone"></i></th>
                                <th class="numeric nmth-after"><i class="fa fa-share"></i></th>
                                <th class="numeric nmth-after"><i class="fa fa-download"></i></th>
                                <th class="nmth-init">Social</th>
                                <th>Rating</th>
                                <? if ($this->viewingOwnProfile) { ?>
                                    <th>Manage</th>
                                <? } else { ?>
                                    <th>View/Clone</th>
                                <? } ?>
                            </tr>
                            </thead>
                            <tbody>
                            <? foreach ($this->routes as $route) { ?>
                                <tr class="routeRow">
                                    <td data-title="Name" class="nmt-large">
                                        <?= $route->name ?>
                                    </td>
                                    <td data-title="Points" class="numeric">
                                        <?= $route->num_points ?>
                                    </td>
                                    <? if ($this->viewingOwnProfile) { ?>
                                        <td data-title="Privacy"><?= ($route->is_private) ? 'Private' : 'Public' ?></td>
                                    <? } ?>

                                    <td data-title="Created">
                                        <?= date("d M y", strtotime($route->created)) ?>
                                    </td>
                                    <td data-title="Comments" class="numeric nmth-after">
                                        <?= $route->comments ?>
                                    </td>
                                    <td data-title="Forks" class="numeric nmth-after">
                                        <?= $route->forks ?>
                                    </td>
                                    <td data-title="Shares" class="numeric nmth-after">
                                        <?= $route->shares ?>
                                    </td>
                                    <td data-title="Downloads" class="numeric nmth-after">
                                        <?= $route->downloads ?>
                                    </td>

                                    <td data-title="Social" class="nmth-init">
                                        <i class="fa fa-comment"></i> <?= $route->comments ?>
                                        <i class="fa fa-code-fork"></i> <?= $route->forks ?>
                                        <i class="fa fa-share"></i> <?= $route->shares ?>
                                        <i class="fa fa-download"></i> <?= $route->downloads ?>
                                    </td>

                                    <td data-title="Rating">
                                        <?= $this->partial('user', 'stars', null, array(
                                            'rating' => $route->rating
                                        )) ?>
                                    </td>
                                    <td data-title="<?= ($this->viewingOwnProfile) ? 'Manage' : 'View/Fork' ?>">
                                        <a class="btnLink" href="/route/detail/id/<?= $route->routeId ?>">
                                            <button class="btn btn-success btn-nopad">
                                                <i class="fa fa-info-circle"></i>
                                            </button>
                                        </a>
                                        <? if ($this->viewingOwnProfile) { ?>
                                            <a class="btnLink" href="/route/create/id/<?= $route->routeId ?>">
                                                <button class="btn btn-primary btn-nopad"><i class="fa fa-pencil"></i>
                                                </button>
                                            </a>
                                            <a class="btnLink" target="_blank" href="/route/download/id/<?= $route->routeId ?>">
                                                <button class="btn btn-warning btn-nopad"><i class="fa fa-download"></i>
                                                </button>
                                            </a>

                                            <a class="delBtn btnLink" href="/route/delete/id/<?= $route->routeId ?>">
                                                <button class="btn btn-danger btn-nopad"><i class="fa fa-trash"></i>
                                                </button>
                                            </a>
                                        <? } else { ?>
                                            <a class="btnLink" href="/route/fork/id/<?= $route->routeId ?>">
                                                <button class="btn btn-warning btn-nopad">
                                                    <i class="fa fa-clone"></i>
                                                </button>
                                            </a>
                                        <? } ?>
                                    </td>
                                </tr>
                            <? } ?>
                            </tbody>
                        </table>
                    </div>
                <? } else { ?>
                    <? if ($this->viewingOwnProfile) { ?>
                        You have not submitted any routes yet. Click below to get started!<br>
                        <br>
                        <a href="/route/create">
                            <button class="btn btn-success">
                                <i class="fa fa-plus"></i> Create Route
                            </button>
                        </a>
                    <? } else { ?>
                        This user has not submitted any routes!
                    <? } ?>
                <? } ?>

            </div>
        </div>
    </div>
    <div class="col-md-2"></div>
</div>
