<h3>User Information</h3>

<p> Username <?= $this->user->username ?> </p>
<p> User id <?= $this->user->userId ?> </p>
<p> First name <?= $this->user->fname ?> </p>
<p> Last name <?= $this->user->lname ?> </p>
<p> Location <?= $this->user->location ?> </p>
<p> Login Count <?= $this->user->loginCount ?> </p>
<p> Is admin <?= $this->user->isAdmin ?> </p>
<p> Is banned <?= $this->user->isBanned ?> </p>
<p> Is shadow banned <?= $this->user->isShadowBanned ?> </p>
<p> Created <?= $this->user->datetimeCreated ?> </p>
<p> Updated <?= $this->user->datetimeUpdated ?> </p>