<div class="row">

    <div class="col-md-8">
        <h3>
            My routes
        </h3>
    </div>
    <div class="col-md-4">
        <a href="/route/create">
            <button class="btn btn-success">
                <i class="fa fa-plus"></i> New Route
            </button>
        </a>
    </div>

    <div class="col-md-10">
        <div class="table-responsive">
            <table class="table" id="routeTable">
                <thead>
                <tr>
                    <th>Name</th>
                    <th>Points</th>
                    <th>Privacy</th>
                    <th>Created</th>
                    <th>Comments</th>
                    <th>Rating</th>
                    <th>Manage</th>
                </tr>
                </thead>
                <tbody>
                <? foreach ($this->routes as $route) { ?>
                    <tr class="routeRow">
                        <td class="hidden routeId"><?= $route->routeId ?></td>
                        <td><?= $route->name ?></td>
                        <td>
                            <?= $route->num_points ?>
                            <i class="fa fa-chevron-circle-down"></i>
                            <i class="fa fa-chevron-circle-up hidden"></i>
                        </td>
                        <td><?= ($route->is_private) ? 'Private' : 'Public' ?></td>
                        <td><?= date("d M y", strtotime($route->created)) ?></td>
                        <td>99</td>
                        <td>
                            <? for ($i = 0; $i < 5; $i++) { ?>
                                <i class="fa fa-star"></i>
                            <? } ?>
                        </td>
                        <td>
                            <a class="btnLink" href="/route/create/id/<?= $route->routeId ?>">
                                <button class="btn btn-primary btn-nopad"><i class="fa fa-pencil"></i></button>
                            </a>
                            <a class="btnLink" target="_blank" href="/user/downloadroute/id/<?= $route->routeId ?>">
                                <button class="btn btn-warning btn-nopad"><i class="fa fa-download"></i></button>
                            </a>

                            <a class="delBtn btnLink" href="/user/deleteroute/id/<?= $route->routeId ?>">
                                <button class="btn btn-danger btn-nopad"><i class="fa fa-trash"></i></button>
                            </a>
                        </td>
                    </tr>
                    <tr class="routeRow hidden">
                        <td colspan="4">
                            <table class="table">
                                <thead>
                                <tr>
                                    <th>Name</th>
                                    <th>Latitude</th>
                                    <th>Longitude</th>
                                </tr>
                                </thead>
                                <? foreach ($route->points as $point) { ?>
                                    <tr>
                                        <td> <?= $point->name ?> </td>
                                        <td> <?= $point->latitude ?> </td>
                                        <td> <?= $point->longitude ?> </td>
                                    </tr>
                                <? } ?>
                            </table>
                        </td>
                    </tr>
                <? } ?>
                </tbody>
            </table>
        </div>
    </div>

    <div class="col-md-4">
        <a href="/route/create">
            <button class="btn btn-success">
                <i class="fa fa-plus"></i> New Route
            </button>
        </a>
    </div>
</div>

