<div class="row">
    <div class="col-sm-1 col-md-2"></div>
    <div class="col-sm-10 col-md-8">
        <? if (!is_null($this->errorMessage)) { ?>
            <div class="alert alert-danger msg" role="alert">
                <i class="fa fa-exclamation-circle"></i>
                <?= $this->errorMessage; ?>
            </div>
        <? } ?>
        <? if (!is_null($this->successMessage)) { ?>
            <div class="alert alert-success msg" role="alert">
                <i class="fa fa-check"></i>
                <?= $this->successMessage; ?>
            </div>
        <? } ?>
    </div>
    <div class="col-md-2"></div>
</div>

<div class="row margin_t_15">
    <div class="col-sm-1 col-md-2"></div>
    <div class="col-sm-10 col-md-8">
        <div class="border-container">
            <div class="title prefTitle">
                Your email preferences
            </div>
            <div class="row">
                <form enctype="application/x-www-form-urlencoded" method="post" action="/user/updatepreferences">
                    <div class="col-md-4 col-md-push-8 col-sm-push-0">
                        <div class="alert alert-info" role="alert">
                            <i class="fa fa-info-circle"></i> <b>Email Preferences</b>
                            <p>
                                These settings determine what actions will trigger an email to be sent to you. If
                                you uncheck all of them, you will never receive an email from Niceway.to.
                            </p>
                        </div>
                    </div>

                    <div class="col-md-8 col-md-pull-4 col-sm-pull-0">
                        <div>
                            <b>Receive emails when...</b>
                        </div>

                        <label class="check">
                            <input type="checkbox" name="email_route_comment"<?=
                            ($this->user->preferences->emailOnRouteComment) ? 'checked' : '' ?>>
                            <span>Someone comments on your routes</span>
                        </label>

                        <label class="check">
                            <input type="checkbox" name="email_route_fork"<?=
                            ($this->user->preferences->emailOnRouteFork) ? 'checked' : '' ?>>
                            <span>Someone forks your routes</span>
                        </label>

                        <label class="check">
                            <input type="checkbox" name="email_route_rate"<?=
                            ($this->user->preferences->emailOnRouteRating) ? 'checked' : '' ?>>
                            <span>Someone rates your routes</span>
                        </label>

                        <label class="check">
                            <input type="checkbox" name="email_announcement"<?=
                            ($this->user->preferences->emailOnAnnouncement) ? 'checked' : '' ?>>
                            <span>Announcements are posted</span>
                        </label>
                        <br>
                        <input id="updateEmails" type="submit" class="btn btn-success" value="Update Preferences"/>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <div class="col-md-2"></div>
</div>

<div class="row">
    <div class="col-sm-1 col-md-2"></div>
    <div class="col-sm-10 col-md-8">
        <div class="border-container">
            <div class="title yourDetailsTitle">
                Update your details
            </div>
            <div class="row">
                <form enctype="application/x-www-form-urlencoded" method="post" action="/user/updateaccountdetails">
                    <div class="col-md-4 col-md-push-8 col-sm-push-0">
                        <div class="alert alert-info" role="alert">
                            <i class="fa fa-info-circle"></i> <b>Your details</b>
                            <p>
                                All of the information you enter here, excluding your email address, will be
                                visible to other users of Niceway.to.
                            </p>
                        </div>
                    </div>

                    <div class="col-md-8 col-md-pull-4 col-sm-pull-0">
                        <label class="noPad">Name</label>
                        <input type="text" class="form-control" name="fname"
                               placeholder="First Name" value="<?= $this->user->fname ?>">
                        <input type="text" class="form-control" name="lname"
                               placeholder="Last Name" value="<?= $this->user->lname ?>">

                        <label>
                            Email <?=
                            ($this->user->isConfirmed) ? "(<i class=\"fa fa-check\"></i> Confirmed)" : "(<i class=\"fa fa-exclamation-circle\"></i> Not Confirmed)"
                            ?>
                        </label>
                        <input type="text" name="email" class="form-control"
                               placeholder="Your email address" value="<?= $this->user->email ?>">

                        <label> Location </label>
                        <input type="text" name="location" class="form-control"
                               placeholder="Your location" value="<?= $this->user->location ?>">

                        <label> Age </label>
                        <input type="text" name="age" class="form-control"
                               placeholder="Your age" value="<?= $this->user->age ?>">

                        <label> Bio </label>
                            <textarea class="form-control" placeholder="A little about yourself" name="bio"><?=
                                $this->user->bio ?></textarea>

                        <input id="updateAccount" type="submit" class="btn btn-success" value="Update Details"/>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <div class="col-md-2"></div>
</div>

<div class="row margin_b_20">
    <div class="col-sm-1 col-md-2"></div>
    <div class="col-sm-10 col-md-8">
        <div class="border-container">
            <div class="title yourPasswordTitle">
                Update your password
            </div>
            <div class="row">
                <form enctype="application/x-www-form-urlencoded" method="post" action="/user/updatepassword">
                    <div class="col-md-4 col-md-push-8 col-sm-push-0">
                        <div class="alert alert-info" role="alert">
                            <i class="fa fa-info-circle"></i> <b>Your password</b>
                            <p>
                                Your password must be at least 6 characters long, and it is recommended you use a
                                combination of characters (upper and lower case), numbers and symbols
                            </p>
                        </div>
                    </div>
                    <div class="col-md-8 col-md-pull-4 col-sm-pull-0">
                        <div class="form-group" id="in_curPassWrapper">
                            <input type="password" class="form-control" name="currentPass" placeholder="Enter Current Password">
                        </div>
                        <div class="form-group" id="in_newPass1Wrapper">
                            <input type="password" class="form-control" name="newPass1" placeholder="Enter New Password">
                        </div>
                        <div class="form-group" id="in_newPass2Wrapper">
                            <input type="password" class="form-control" name="newPass2" placeholder="Confirm New Password">
                        </div>
                        <input id="updatePassword" type="submit" class="btn btn-success" value="Change Password"/>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <div class="col-md-2"></div>
</div>

