<style>
    .dp_container {
        position: relative;
        left: 0;
        top: 0;
    }

    .dp_container .dp_person {
        position: relative;
        background-color: white;
    }

    .dp_container .dp_skin {
        position: absolute;
    }

    .dp_container .dp_person, .dp_skin {
        max-height: 350px !important;
        top: 0;
        left: 0;
    }

    .dp_container .img-thumbnail.dp_person,
    .dp_container .img-thumbnail.dp_skin {
        -webkit-transition: none;
        transition: none;
    }

    .dp_container .img-thumbnail {
        background-color:transparent;
    }
</style>

<input type="hidden" id="max_size" value="<?= $this->maxScreenSize ?>">

<div class="dp_container">
    <img src="/images/user_icons/default.png" class="img-thumbnail dp_person"/>
    <? foreach ($this->skins as $skin) { ?>
        <img id="skin_<?= $skin->slot_name ?>" src="/images/user_icons/<?= $skin->img ?>"
             class="img-thumbnail dp_skin"/>
    <? } ?>
</div>



