<div class="row">
    <div class="col-md-4">
        <div class="row" id="formIndent">
            <h3> Add a new purchase </h3>
            <form role="form" id="newPurchaseForm" method="post"
                  action="<?= $this->url(array('controller' => 'purchase', 'action' => 'addpurchase'), null, true); ?>">
                <div class="form-group">
                    <label for="inputItems">Items Purchased</label>
                    <input name="itemName" type="text" class="form-control" id="inputItems"
                           placeholder="Enter items purchased" onKeyPress="edValueKeyPress()"
                           onKeyUp="edValueKeyPress()">
                </div>
                
                <div class="form-group">
                    <label for="inputCost">Cost of items</label>
                    <div class="input-group">
                        <div class="input-group-addon">£</div>
                        <input name="itemCost" class="form-control" type="number" step="any" id="inputCost"
                               placeholder="Cost of item" onKeyPress="edValueKeyPress()" onKeyUp="edValueKeyPress()">
                    </div>
                </div>

                <div class="form-group">
                    <label for="inputCat"> Category </label>
                    <select name="inputCat" class="form-control" id="inputCat">
                        <? foreach ($this->purchaseCategories as $category) { ?>
                            <option value="<?= $category->id ?>"> <?= $category->name ?></option>
                        <? } ?>
                    </select>
                </div>

                <input id="addNewSubmit" type="submit" disabled class="btn btn-success" name="addnewsubmit"
                       value="Submit"/>
            </form>
        </div>
    </div>
    <? if ($this->user->userType == 0) { ?>
        <div class="col-md-4">
            <div class="row" id="formIndent">
                <h3> Presets </h3>
                    <input id="addBusPurchase" type="button" class="btn btn-success" value="Bus"/>
                </form>
            </div>
        </div>    
    <? } ?>
</div>