<div class="row row-centered">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Filter and Sort
            </div>
            <div class="panel-body">
                <div class="col-md-9">
                    <div class="row">
                        <div class="col-md-12 ">
                            <label>Categories</label>
                            <div class="b_margin_10">
                                <? foreach ($this->purchaseCategories as $category) { ?>
                                    <button id="<?= $category->id ?>" class="filterOpt btn btn-primary">
                                        <?= $category->name ?>
                                    </button>
                                <? } ?>
                            </div>
                            <button class="btn btn-success" id='checkAll'>Select All</button>
                            <button class="btn btn-danger" id='uncheckAll'>Select None</button>
                        </div>
                        <div class="col-md-12 b_margin_10 t_margin_10">
                            <label>Cost Range</label>
                            <div id="amount"></div>
                            <div id="costSlider" min="<?= is_null($this->minCost) ? 0 : $this->minCost ?>" max="<?= is_null($this->maxCost) ? 0 : $this->maxCost ?>"></div>
                        </div>
                        <div class="col-md-6">
                            <label>Start Date</label>
                            <div class="form-group" id="datepickerMinWrapper">
                                <input class="form-control" id="datepickerMin" type="text" value="<?= is_null($this->defaultMinDate) ? $this->minDate : $this->defaultMinDate ?>">
                            </div>
                        </div>
                        <div class="col-md-6">
                            <label>End Date</label>
                            <div class="form-group" id="datepickerMaxWrapper">
                                <input class="form-control" id="datepickerMax" type="text" value="<?= is_null($this->defaultMaxDate) ? $this->maxDate : $this->defaultMaxDate ?>">
                            </div>
                        </div>

                        <div class="col-md-6">
                            <label>Order By</label>
                            <div class="form-group" id="sortByWrapper">
                                <select name="sortBy" class="form-control" id="sortBy">
                                    <option value="datetime_purchased">Purchase Date</option>
                                    <option value="items">Items</option>
                                    <option value="cost">Cost</option>
                                    <option value="category">Category</option>
                                </select>
                            </div>
                        </div>

                        <div class="col-md-6">
                            <label>Order Direction</label>
                            <div class="form-group" id="sortByDirWrapper">
                                <select name="sortByDir" class="form-control" id="sortByDir">
                                    <option value="asc">Ascending</option>
                                    <option value="desc">Descending</option>
                                </select>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="rowCountContainer">
                        There were
                        <div id="rowCount"></div>
                        results
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="table-responsive">
            <table class="table">
                <thead>
                <tr>
                    <th>Date</th>
                    <th>Items</th>
                    <th>Cost</th>
                    <th>Category</th>
                    <th>Manage</th>
                </tr>

                </thead>
                <tbody id="archive_tbody">
                <tr>
                    <td colspan="5" style="margin-left:auto; margin-right:auto;">
                        <img src="/images/global/loading.gif" class="loading" id="archive_loading">
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>

