<div class="row">
    <div class="col-md-8">
        <div class="panel panel-default">
            <div class="panel-heading">
                Loans
            </div>
            <div class="panel-body">
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                        <tr>
                            <td>Loaner</td>
                            <td>Loaned To</td>
                            <td>Loaned</td>
                            <td>Remaining</td>
                            <td>Last Updated</td>
                            <td>Status</td>
                            <td>Sent By</td>
                            <td></td>
                        </tr>
                        </thead>
                        <tbody id="loanTableTbody">
                            <? foreach ($this->loans as $loan) { ?>
                                <tr class="tableRow">
                                    <td> <?= $loan->loaner ?> </td>
                                    <td> <?= $loan->loanee ?> </td>
                                    <td> &pound;<?= $loan->total_amount ?> </td>
                                    <td>
                                        &pound;<?= number_format($loan->amount_remaining, 2) ?>
                                        (<?= number_format(($loan->amount_remaining/$loan->total_amount) * 100) ?>%)
                                    </td>
                                    <td> <?= date('d M Y H:i:s', strtotime($loan->last_updated)) ?> </td>
                                    <td>
                                        <? if (!is_null($loan->receiver_title)
                                            && ($this->user->userId != $loan->owner)) { ?>
                                            <?= $loan->receiver_title ?>
                                        <? } else if ($loan->loanee_id == $this->user->userId) { ?>
                                            <?= $loan->loanee_title ?>
                                        <? } else { ?>
                                            <?= $loan->loaner_title ?>
                                        <? } ?>
                                    </td>
                                    <td> <?= $loan->owner_name ?></td>
                                    <td> <span class="fa fa-caret-down cPointer"></span> </td>
                                    <input type="hidden" value="<?= $loan->step_id ?>" class="step_id">
                                </tr>
                                <tr class="hidden">
                                    <td colspan="8">
                                        <?= $this->partial('purchase', 'loansteps', array(
                                            'stepNum' => $loan->step_id,
                                            'steps'   => $this->loanSteps,
                                            'owed'    => $loan->loaner === "You",
                                            'owner'   => $loan->owner,
                                            'userId'  => $this->user->userId,
                                            'loan'    => $loan
                                        )); ?>
                                    </td>
                                </tr>
                            <? } ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                New Loan
            </div>
            <div class="panel-body">
                <form id="newLoanForm" method="post" action="/purchase/newloan">
                    <select id="tofromSelector" name="tofromInput" class="form-control fc">
                        <option value="owed"> I have lent </option>
                        <option value="owe"> I have borrowed </option>
                    </select>

                    <label>Amount</label>
                    <div class="input-group fc">
                        <span class="input-group-addon" id="pound_addon">&pound;</span>
                        <input type="number" class="form-control" name="amountInput"
                               aria-describedby="pound_addon">
                    </div>

                    <label id="tofromLabel"> To </label>
                    <input class="form-control fc" type="text" name="toInput" id="toInput" placeholder="Username">

                    <input type="submit" class="btn btn-success right">
                </form>
            </div>
        </div>
    </div>
</div>