<?= $this->doctype() ?>
<? $c = Zend_Controller_Front::getInstance()->getRequest()->getControllerName(); ?>
<? $a = Zend_Controller_Front::getInstance()->getRequest()->getActionName(); ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title><?= $this->title ?></title>
    <?
    $cssFiles = array(
        '/libs/JQuery/jquery-ui.css',
        '/libs/Bootstrap/bootstrap.min.css',
        '/libs/magnific/magnific-popup.css',
        '/libs/TimePicker/jquery.timepicker.css',
        '/libs/font-awesome-4.3.0/css/font-awesome.min.css',
        '/css/global.css',
        '/css/' . $c . '/global.css',
        '/css/' . $c . '/' . $a . '.css'
    );

    foreach ($cssFiles as $cssFile) {
        if (file_exists(getcwd() . $cssFile)) {
            $this->headLink()->appendStylesheet($cssFile);
        }
    }
    echo $this->headLink();
    ?>
</head>
<body>

<? if ($this->hasTopBar) { ?>
    <nav class="navbar navbar-inverse" role="navigation">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target="#navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand"
                   href="<?= $this->url(array('action' => 'index', 'controller' => 'engage'), null, true) ?>">Engage</a>
            </div>

            <div class="collapse navbar-collapse" id="navbar-collapse">
                <? if ($this->hasNavBar) { ?>
                    <ul class="nav navbar-nav navbar-left">
                        <? foreach ($this->links as $link) { ?>
                            <? if (isset($this->user) && $this->user->userType == 1 && property_exists($link, 'isAdminOnly')) { ?>
                                <? continue; ?>
                            <? } ?>
                            <li class="<?= ($link->action == $a) ? 'active' : '' ?>">
                                <a href="<?= $this->url(array('action' => $link->action, 'controller' => $link->controller), null, true); ?>">
                                    <?= $link->name ?>
                                </a>
                            </li>
                        <? } ?>
                    </ul>
                <? } ?>
                <? if (!$this->isExternal) { ?>
                    <ul class="nav navbar-nav navbar-right">
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                Logged in as <?= $this->user->name ?> <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu" role="menu">
                                <li>
                                    <a href="<?= $this->url(array('action' => 'index', 'controller' => 'account'), null, true) ?>">
                                        My Account
                                    </a>
                                </li>
                                <? if ($this->user->userType == 0) { ?>
                                    <li>
                                        <a href="<?= $this->url(array('action' => 'index', 'controller' => 'tools'), null, true) ?>">
                                            Admin Tools
                                        </a>
                                    </li>
                                <? } ?>
                                <li>
                                    <a href="<?= $this->url(array('action' => 'logout', 'controller' => 'login'), null, true) ?>">
                                        Log Out
                                    </a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                <? } ?>
            </div>
        </div>
    </nav>
<? } ?>

<? if (count($this->siren) > 0) { ?>
    <? foreach($this->siren as $siren) {?>
        <div id="siren">
            <div class="alert alert-danger" role="alert">
                <?= $siren->message; ?>
            </div>
        </div>
    <? } ?>
<? } ?>

<? if (!(is_null($this->errors)) && count($this->errors) != 0) { ?>
    <? foreach ($this->errors as $error) { ?>
        <?= $error ?>
    <? } ?>
<? } ?>

<? try { // Try to get any potential custom layout ?>
    <?= $this->render('/' . $c . '.phtml'); ?>
<? } catch (Exception $e) { ?>
    <?= $this->layout()->content; ?>
<? } ?>

<?
$jsFiles = array(
    '/libs/JQuery/jquery.js',
    '/libs/JQuery/jquery-extended.js',
    '/libs/JQuery/jquery-ui.js',
    '/libs/Bootstrap/bootstrap.min.js',
    '/libs/Highchart/highcharts.js',
    '/libs/magnific/magnific.js',
    '/libs/TimePicker/jquery.timepicker.js',
    '/libs/Momentjs/moment.min.js',
    '/js/global.js',
    '/js/' . $c . '/global.js',
    '/js/' . $c . '/' . $a . '.js'
);

foreach ($jsFiles as $jsFile) {
    if (file_exists(getcwd() . $jsFile)) {
        $this->headScript()->appendFile($jsFile, 'text/javascript');
    }
}
echo $this->headScript();
?>
</body>
</html>
