<?= $this->doctype() ?>

<? // Get controller/action so we can render css and js?>
<? $c = Zend_Controller_Front::getInstance()->getRequest()->getControllerName(); ?>
<? $a = Zend_Controller_Front::getInstance()->getRequest()->getActionName(); ?>

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <title> <?= $this->title ?> </title>

        <? /* Create an array of css files and import them if they exist */
            $cssFiles = array(
                '/libs/JQuery/jquery-ui.css',
                '/libs/Bootstrap/bootstrap.min.css',
                '/libs/magnific/magnific-popup.css',
                '/libs/font-awesome-4.3.0/css/font-awesome.min.css',
                '/libs/mapbox/mapbox.css',
                '/libs/leaflet/leaflet.css',
                '/css/global.css',
                '/css/' . $c . '/global.css',
                '/css/' . $c . '/' . $a . '.css'
            );

            foreach ($cssFiles as $cssFile) {
                if (file_exists(getcwd() . $cssFile)) {
                    $this->headLink()->appendStylesheet($cssFile);
                }
            }
            echo $this->headLink();
        ?>
    </head>
    <body>

    <? // Display the content of the HTML page?>
    <?= $this->layout()->content; ?>
    <? /* Create an array of js files and import them if they exist */
        $jsFiles = array(
            '/libs/JQuery/jquery.js',
            '/libs/JQuery/jquery-extended.js',
            '/libs/JQuery/jquery-ui.js',
            '/libs/Bootstrap/bootstrap.min.js',
            '/libs/magnific/magnific.js',
            '/libs/mapbox/mapbox.js',
            '/libs/leaflet/leaflet.js',
            '/js/global.js',
            '/js/' . $c . '/global.js',
            '/js/' . $c . '/' . $a . '.js'
        );

        foreach ($jsFiles as $jsFile) {
            if (file_exists(getcwd() . $jsFile)) {
                $this->headScript()->appendFile($jsFile, 'text/javascript');
            }
        }
        echo $this->headScript();
    ?>
    </body>
</html>